"""N-PORT DERA/XML parsing, accession revisions, votes and consensus (SYNTHETIC rows).

Header lines of the six pinned tables are the real Stage 1A 2021q1/2026q2 vintages.
"""

from __future__ import annotations

import dataclasses
import datetime as dt
import hashlib
import importlib.util
import json
import subprocess
import sys
import uuid
import zipfile
from collections import Counter, defaultdict
from collections.abc import Iterable
from pathlib import Path

import pytest

pytest.importorskip("duckdb")
pytest.importorskip("pyarrow")

from src.bonds.default_events import contracts as c
from src.bonds.default_events import nport
from src.bonds.default_events import sec_acquisition as sa

ROOT = Path(__file__).resolve().parents[1]
_SPEC = importlib.util.spec_from_file_location(
    "dera_builder", ROOT / "tests" / "fixtures" / "bond_default_events" / "nport" / "dera_builder.py"
)
b = importlib.util.module_from_spec(_SPEC)
assert _SPEC.loader is not None
_SPEC.loader.exec_module(b)

UTC = dt.timezone.utc
RETRIEVED = dt.datetime(2026, 9, 25, 3, 14, tzinfo=UTC)
K = dt.datetime(2026, 9, 25, 23, 0, tzinfo=UTC)
CUSIP_A = b.make_cusip("03783310")
CUSIP_B = b.make_cusip("59491810")


def run(tmp_path: Path, filings: list, *, label: str = "2021q1_nport.zip", vintage: str = "2021q1",
        retrieved: dt.datetime = RETRIEVED, **zip_kwargs) -> nport.DeraPackageResult:
    tag = uuid.uuid4().hex[:6]
    path = tmp_path / f"{tag}_{label}"
    sha = b.build_zip(path, b.tables(filings), vintage=vintage, **zip_kwargs)
    return nport.parse_dera_package(
        path, expected_sha256=sha, package_label=label, output_dir=tmp_path / f"out_{tag}",
        work_dir=tmp_path / "work", retrieved_at=retrieved, duckdb_threads=2, duckdb_memory_limit="512MB",
    )


def observations(result: nport.DeraPackageResult, **kwargs) -> list[c.CreditObservation]:
    return list(nport.iter_package_observations(result, **kwargs))


def filing(n: int, cik: str = "0000000101", series: str | None = "S000000001", **kwargs) -> object:
    return b.Filing(f"00000000{n:02d}-21-000001", cik=cik, series=series, **kwargs)


# --- vintages, layout and quarantine ---------------------------------------------
def test_stage1a_vintage_headers_carry_required_columns() -> None:
    for name, vintage in b.VINTAGES.items():
        for table, columns in nport.REQUIRED_COLUMNS.items():
            header = vintage["headers"][f"{table}.tsv"].split("\t")
            assert set(columns) <= set(header), (name, table)
        assert vintage["headers"]["DEBT_SECURITY.tsv"].split("\t") == list(nport.DEBT_REQUIRED_COLUMNS)
    assert "FUND_VAR_INFO.tsv" not in b.VINTAGES["2021q1_nport.zip"]["members"]
    assert "FUND_VAR_INFO.tsv" in b.VINTAGES["2026q2_nport.zip"]["members"]


@pytest.mark.parametrize("vintage", ["2021q1", "2026q2"])
def test_both_vintages_parse(tmp_path: Path, vintage: str) -> None:
    result = run(tmp_path, [filing(1).hold(1, CUSIP_A)], vintage=vintage, label=f"{vintage}_nport.zip")
    assert result.status == "parsed", result.quarantine_reasons
    assert result.stats["optional_members_present"]["FUND_VAR_INFO.tsv"] is (vintage == "2026q2")
    package = result.source_package
    assert package.source_family == "sec_nport_dera" and package.content_sha256 == result.zip_sha256
    assert set(package.member_sha256s) == {f"{t}.tsv" for t in nport.PINNED_TABLES}
    assert package.public_time_basis == "first_verified_retrieval"
    assert package.first_verified_public_at == RETRIEVED  # regenerated bytes are not old availability
    assert package.effective_coverage_start == dt.date(2021, 3, 31)


def test_package_hash_mismatch_raises(tmp_path: Path) -> None:
    path = tmp_path / "p.zip"
    b.build_zip(path, b.tables([filing(1).hold(1, CUSIP_A)]))
    with pytest.raises(nport.PackageIntegrityError):
        nport.parse_dera_package(path, expected_sha256="0" * 64, package_label="p", output_dir=tmp_path / "o",
                                 work_dir=tmp_path / "w", retrieved_at=RETRIEVED)


def test_member_hash_reverification(tmp_path: Path) -> None:
    result = run(tmp_path, [filing(1).hold(1, CUSIP_A)])
    zip_path = next(tmp_path.glob("*_2021q1_nport.zip"))
    members = dict(result.source_package.member_sha256s)
    nport.verify_member_hashes(zip_path, expected_sha256=result.zip_sha256, expected_members=members)
    tampered = {**members, "DEBT_SECURITY.tsv": "0" * 64}
    with pytest.raises(nport.PackageIntegrityError, match="member_sha256_mismatch:DEBT_SECURITY.tsv"):
        nport.verify_member_hashes(zip_path, expected_sha256=result.zip_sha256, expected_members=tampered)
    with pytest.raises(nport.PackageIntegrityError, match="member_missing"):
        nport.verify_member_hashes(zip_path, expected_sha256=result.zip_sha256,
                                   expected_members={**members, "X.tsv": "0" * 64})
    with pytest.raises(nport.PackageIntegrityError, match="package_sha256_mismatch"):
        nport.verify_member_hashes(zip_path, expected_sha256="1" * 64, expected_members=members)


def test_missing_debt_table_quarantines(tmp_path: Path) -> None:
    result = run(tmp_path, [filing(1).hold(1, CUSIP_A)], omit=["DEBT_SECURITY.tsv"])
    assert result.status == "quarantined"
    assert "member_missing:DEBT_SECURITY.tsv" in result.quarantine_reasons
    assert result.projection_path is None


def test_missing_required_debt_column_quarantines(tmp_path: Path) -> None:
    header = [c for c in nport.DEBT_REQUIRED_COLUMNS if c != "IS_ANY_PORTION_INTEREST_PAID"] + ["IS_PAID_KIND"]
    f = filing(1).hold(1, CUSIP_A)
    for row in f.debts:
        row["IS_PAID_KIND"] = row.pop("IS_ANY_PORTION_INTEREST_PAID")
    result = run(tmp_path, [f], headers={"DEBT_SECURITY": header})
    assert result.status == "quarantined"
    assert any(r.startswith("required_columns_missing:DEBT_SECURITY.tsv:IS_ANY_PORTION_INTEREST_PAID")
               for r in result.quarantine_reasons)


def test_unknown_future_columns_are_preserved_in_metadata(tmp_path: Path) -> None:
    header = list(nport.DEBT_REQUIRED_COLUMNS) + ["IS_FUTURE_FLAG"]
    result = run(tmp_path, [filing(1).hold(1, CUSIP_A)], headers={"DEBT_SECURITY": header})
    assert result.status == "parsed"
    assert result.stats["extra_columns"]["DEBT_SECURITY"] == ["IS_FUTURE_FLAG"]
    assert "IS_FUTURE_FLAG" in result.stats["headers"]["DEBT_SECURITY"]


@pytest.mark.parametrize(
    ("mutate", "reason"),
    [
        (lambda t: t["FUND_REPORTED_HOLDING"].append(dict(t["FUND_REPORTED_HOLDING"][0])), "holding_duplicate_ids"),
        (lambda t: t["DEBT_SECURITY"].append(dict(t["DEBT_SECURITY"][0])), "debt_duplicate_ids"),
        (lambda t: t["DEBT_SECURITY"].append({**t["DEBT_SECURITY"][0], "HOLDING_ID": "999"}), "debt_orphans"),
        (lambda t: t["REGISTRANT"].clear(), "holding_accessions_without_registrant"),
        (lambda t: t["SUBMISSION"].append(dict(t["SUBMISSION"][0])), "submission_duplicate_accessions"),
        (lambda t: t["FUND_REPORTED_INFO"].clear(), "holding_accessions_without_fund_info"),
    ],
)
def test_join_and_cardinality_violations_quarantine(tmp_path: Path, mutate, reason: str) -> None:
    tables = b.tables([filing(1).hold(1, CUSIP_A).hold(2, CUSIP_B)])
    mutate(tables)
    path = tmp_path / "p.zip"
    sha = b.build_zip(path, tables)
    result = nport.parse_dera_package(path, expected_sha256=sha, package_label="p.zip", output_dir=tmp_path / "o",
                                      work_dir=tmp_path / "w", retrieved_at=RETRIEVED, duckdb_threads=2)
    assert result.status == "quarantined"
    assert any(r.startswith(f"cardinality:{reason}=") for r in result.quarantine_reasons), result.quarantine_reasons


def test_zip_traversal_and_expansion_bounds(tmp_path: Path) -> None:
    path = tmp_path / "evil.zip"
    with zipfile.ZipFile(path, "w") as archive:
        archive.writestr("../evil.tsv", b"x")
    sha = nport.sha256_file(path)
    with pytest.raises(nport.ZipSafetyError):
        nport.parse_dera_package(path, expected_sha256=sha, package_label="e", output_dir=tmp_path / "o",
                                 work_dir=tmp_path / "w", retrieved_at=RETRIEVED)
    big = tmp_path / "big.zip"
    sha = b.build_zip(big, b.tables([filing(1).hold(1, CUSIP_A)]))
    with pytest.raises(nport.ZipSafetyError):
        nport.parse_dera_package(big, expected_sha256=sha, package_label="b", output_dir=tmp_path / "o2",
                                 work_dir=tmp_path / "w", retrieved_at=RETRIEVED,
                                 limits=nport.ZipLimits(max_member_bytes=64))
    bomb = tmp_path / "bomb.zip"
    with zipfile.ZipFile(bomb, "w", compression=zipfile.ZIP_DEFLATED) as archive:
        archive.writestr("SUBMISSION.tsv", b"A" * 5_000_000)
    with pytest.raises(nport.ZipSafetyError):
        nport.inspect_zip(zipfile.ZipFile(bomb), nport.ZipLimits(max_compression_ratio=100))


# --- lexical fidelity, identity, eligibility ---------------------------------------
def test_flag_presence_states_and_lexical_values(tmp_path: Path) -> None:
    f = filing(1)
    f.hold(1, CUSIP_A, is_default="Y", arrears=None, pik="X")
    f.hold(2, CUSIP_B, is_default=None, arrears="Y", pik="y", title='A "quoted" title')
    result = run(tmp_path, [f])
    rows = {o.holding_id: o for o in observations(result)}
    one, two = rows["1"], rows["2"]
    assert one.nport_is_default == "Y" and one.field_presence["nport_is_default"] == "present"
    assert one.nport_arrears_or_deferral is None and one.field_presence["nport_arrears_or_deferral"] == "null"
    assert one.nport_paid_in_kind == "X" and one.field_presence["nport_paid_in_kind"] == "invalid"
    assert two.nport_is_default is None and two.field_presence["nport_is_default"] == "null"
    assert two.nport_paid_in_kind == "y" and two.field_presence["nport_paid_in_kind"] == "invalid"
    projection = {r["holding_id"]: r for r in nport.iter_projection_rows(result.projection_path)}
    assert projection["2"]["issuer_title"] == 'A "quoted" title'
    counts = result.stats["eligible_flag_counts"]
    assert counts["IS_DEFAULT"] == {"Y": 1, "null": 1}
    assert counts["IS_ANY_PORTION_INTEREST_PAID"] == {"invalid": 2}


@pytest.mark.parametrize(
    ("cusip", "isins", "expected", "status"),
    [
        (CUSIP_A, [], CUSIP_A, "valid_cusip"),
        (CUSIP_A[:8] + str((int(CUSIP_A[8]) + 1) % 10), [], None, "invalid_cusip"),
        (CUSIP_A + "1", [], None, "invalid_cusip"),  # never truncated
        ("N/A", [b.make_isin(CUSIP_A)], CUSIP_A, "isin_derived"),
        ("000000000", [b.make_isin(CUSIP_A)], CUSIP_A, "isin_derived"),  # checksum-valid placeholder
        ("000000000", [], None, "missing"),
        (None, [b.make_isin(CUSIP_A, "CA")], CUSIP_A, "isin_derived"),
        (CUSIP_A, [b.make_isin(CUSIP_B)], None, "conflict_cusip_isin"),
        ("N/A", [b.make_isin(CUSIP_A), b.make_isin(CUSIP_B)], None, "conflict_multiple_isins"),
        ("N/A", ["GB00B03MLX29"], None, "non_us_ca_isin"),
        ("N/A", ["US0378331006"], None, "invalid_isin"),
        (CUSIP_A[:8] + "X", [b.make_isin(CUSIP_A)], None, "invalid_cusip"),  # malformed never repaired
    ],
)
def test_identity_resolution(cusip, isins, expected, status) -> None:
    resolved = nport.resolve_identity(cusip, isins)
    assert (resolved.cusip9, resolved.status) == (expected, status)


def test_identifiers_aggregated_before_join_no_fan_out(tmp_path: Path) -> None:
    isin = b.make_isin(CUSIP_A)
    f = filing(1).hold(1, "N/A", isins=[isin, isin]).hold(2, "N/A", isins=[isin, b.make_isin(CUSIP_B)])
    result = run(tmp_path, [f])
    rows = observations(result)
    assert len(rows) == 2
    by_id = {o.holding_id: o for o in rows}
    assert by_id["1"].cusip9 == CUSIP_A and by_id["1"].isin_raw == isin
    assert by_id["2"].cusip9 is None and by_id["2"].isin_raw is None
    assert result.stats["identifiers"]["duplicate_isin_rows"] == 1
    assert result.stats["identifiers"]["debt_holdings_with_multiple_distinct_isins"] == 1


def test_corp_dbt_eligibility_with_exclusion_counts(tmp_path: Path) -> None:
    f = filing(1).hold(1, CUSIP_A, is_default="Y").hold(2, CUSIP_B, is_default="Y", issuer_type="MUN")
    f.hold(3, CUSIP_B, asset_cat="LON", is_default="Y").hold(4, CUSIP_B, debt=False)
    result = run(tmp_path, [f])
    assert [o.holding_id for o in observations(result)] == ["1"]
    category = result.stats["debt_by_category"]
    assert category["eligible_corp_dbt_rows"] == 1 and category["excluded_rows"] == 2
    assert category["excluded_is_default_y_rows"] == 2


def test_package_local_holding_ids_reused_across_packages(tmp_path: Path) -> None:
    first = run(tmp_path, [filing(1).hold(7, CUSIP_A)], label="2021q1_nport.zip")
    second = run(tmp_path, [filing(2, cik="0000000102", series="S000000002").hold(7, CUSIP_A)],
                 label="2021q2_nport.zip")
    a, bb = observations(first)[0], observations(second)[0]
    assert a.holding_id == bb.holding_id == "7"
    assert a.observation_id != bb.observation_id and a.semantic_key != bb.semantic_key


def test_regenerated_package_time_is_retrieval_not_filing_date(tmp_path: Path) -> None:
    obs = observations(run(tmp_path, [filing(1).hold(1, CUSIP_A)]))[0]
    assert obs.public_time_basis == "first_verified_retrieval"
    assert obs.public_available_at == RETRIEVED and obs.first_seen_at == RETRIEVED
    assert obs.report_date == dt.date(2021, 3, 31) and obs.acceptance_raw is None


def _dera_header(accession: str, *, form: str = "NPORT-P", cik: str = "0000000101",
                 raw: str = "20210520163000") -> sa.AcceptanceHeader:
    doc = (f"<SEC-HEADER>\n<ACCEPTANCE-DATETIME>{raw}\n<ACCESSION-NUMBER>{accession}\n<TYPE>{form}\n"
           f"<CIK>{cik}\n</SEC-HEADER>").encode()
    return sa.parse_acceptance_header(doc, accession_number=accession, url="u", document_sha256="0" * 64,
                                      retrieved_at=RETRIEVED)


def test_matching_header_alone_is_acceptance_metadata_not_availability(tmp_path: Path) -> None:
    result = run(tmp_path, [filing(1).hold(1, CUSIP_A)])
    accession = "0000000001-21-000001"
    notes = __import__("collections").Counter()
    good = observations(result, acceptance_headers={accession: _dera_header(accession)}, time_notes=notes)[0]
    assert good.public_time_basis == "first_verified_retrieval" and good.public_available_at == RETRIEVED
    assert good.acceptance_raw == "20210520163000"  # kept as separate metadata
    assert good.acceptance_at == dt.datetime(2021, 5, 20, 20, 30, tzinfo=UTC)
    assert notes == {"acceptance_metadata_only": 1}
    for bad in (_dera_header(accession, form="NPORT-NP"), _dera_header(accession, form="NPORT-P/A"),
                _dera_header(accession, cik="0000000999")):
        obs = observations(result, acceptance_headers={accession: bad})[0]
        assert obs.public_time_basis == "first_verified_retrieval" and obs.acceptance_raw is None


def test_changed_dera_flag_under_unchanged_header_cannot_be_backdated(tmp_path: Path) -> None:
    """Regenerated DERA content that differs from the public filing keeps package availability."""
    dera = xml_twin_dera(tmp_path, is_default="N")  # public XML says Y
    header = xml_header(filing_date="20260812")
    xml = nport.parse_public_accession(xml_doc(), header=header, retrieved_at=RETRIEVED, official_url="u")
    with pytest.raises(nport.ReconciliationError, match="semantic_digest_mismatch"):
        nport.reconcile_dera_with_public(dera, xml)
    obs = [o for o in observations(dera, acceptance_headers={header.accession_number: header})
           if o.cusip9 == CUSIP_A]
    assert all(o.public_time_basis == "first_verified_retrieval" and o.public_available_at == RETRIEVED
               for o in obs)


def test_reconciled_equal_dera_content_can_be_backdated(tmp_path: Path) -> None:
    dera = xml_twin_dera(tmp_path)
    header = xml_header(filing_date="20260812")
    xml = nport.parse_public_accession(xml_doc(), header=header, retrieved_at=RETRIEVED, official_url="u")
    rec = nport.reconcile_dera_with_public(dera, xml)
    assert rec.dera_package_id == str(dera.source_package.package_id) and rec.dera_zip_sha256 == dera.zip_sha256
    assert rec.xml_sha256 == xml.source_package.content_sha256 and rec.header_sha256 == header.header_sha256
    stored = nport.DeraReconciliation.from_record(json.loads(json.dumps(rec.to_record())))
    assert stored == rec
    notes = __import__("collections").Counter()
    (obs,) = [o for o in observations(dera, acceptance_headers={header.accession_number: header},
                                      reconciliations=[stored], time_notes=notes) if o.cusip9 == CUSIP_A]
    assert obs.public_time_basis == "edgar_acceptance_datetime"
    assert obs.public_available_at == dt.datetime(2026, 8, 12, 14, 15, tzinfo=UTC)
    assert notes == {"reconciled_with_public_xml": 1}
    tampered = dataclasses.replace(stored, dera_semantic_digest="0" * 64)
    with pytest.raises(nport.ReconciliationError):
        list(nport.iter_package_observations(dera, acceptance_headers={header.accession_number: header},
                                             reconciliations=[tampered]))
    other_header = dataclasses.replace(header, header_sha256="f" * 64)
    (unbound,) = [o for o in observations(dera, acceptance_headers={header.accession_number: other_header},
                                          reconciliations=[stored]) if o.cusip9 == CUSIP_A]
    assert unbound.public_time_basis == "first_verified_retrieval"  # reconciliation bound to another header


def test_projection_and_observations_are_deterministic_in_fresh_processes(tmp_path: Path) -> None:
    path = tmp_path / "det.zip"
    sha = b.build_zip(path, b.tables([filing(1).hold(1, CUSIP_A, is_default="Y").hold(2, "N/A",
                                      isins=[b.make_isin(CUSIP_B)]), filing(2, cik="0000000102").hold(3, CUSIP_A)]))
    script = (
        "import sys, json, datetime as dt\n"
        f"sys.path.insert(0, {str(ROOT)!r})\n"
        "from pathlib import Path\n"
        "from src.bonds.default_events import nport, contracts as c\n"
        "out = Path(sys.argv[1])\n"
        f"r = nport.parse_dera_package(Path({str(path)!r}), expected_sha256={sha!r}, package_label='d.zip',"
        " output_dir=out, work_dir=out / 'w', retrieved_at=dt.datetime(2026,9,25,tzinfo=dt.timezone.utc),"
        " duckdb_threads=2)\n"
        "print(c.frame_digest(o.row_sha256() for o in nport.iter_package_observations(r)))\n"
    )
    digests = []
    for i in range(2):
        done = subprocess.run([sys.executable, "-c", script, str(tmp_path / f"run{i}")], capture_output=True,
                              text=True, timeout=240, check=False)
        assert done.returncode == 0, done.stderr[-2000:]
        digests.append(done.stdout.strip())
    assert digests[0] == digests[1] and digests[0].startswith("sha256:")


# --- public primary_doc.xml ----------------------------------------------------------
def xml_doc(*, sub_type: str = "NPORT-P", debt: str | None = None, cik: str = "0000000101",
            namespace: str = "http://www.sec.gov/edgar/nport", prefix: str = "") -> bytes:
    debt = debt if debt is not None else (
        "<debtSec><maturityDt>2030-01-15</maturityDt><couponKind>Fixed</couponKind>"
        "<annualizedRt>5.0</annualizedRt><isDefault>Y</isDefault><areIntrstPmntsInArrs></areIntrstPmntsInArrs>"
        "</debtSec>"
    )
    return (
        f'{prefix}<?xml version="1.0" encoding="UTF-8"?>'
        f'<edgarSubmission xmlns="{namespace}" xmlns:com="http://www.sec.gov/edgar/common" '
        'xmlns:ncom="http://www.sec.gov/edgar/nportcommon">'
        f"<headerData><submissionType>{sub_type}</submissionType><filerInfo><filer><issuerCredentials>"
        f"<cik>{cik}</cik></issuerCredentials></filer></filerInfo></headerData>"
        f"<formData><genInfo><regCik>{cik}</regCik><seriesId>S000000001</seriesId>"
        "<repPdDate>2026-06-30</repPdDate></genInfo><invstOrSecs>"
        f"<invstOrSec><name>Synthetic</name><lei>N/A</lei><title>NOTE</title><cusip>{CUSIP_A}</cusip>"
        "<identifiers><isin value=\"US0378331005\"/></identifiers><balance>1000</balance><units>PA</units>"
        "<curCd>USD</curCd><valUSD>990</valUSD><assetCat>DBT</assetCat><issuerCat>CORP</issuerCat>"
        f"{debt}</invstOrSec>"
        "<invstOrSec><name>Muni</name><cusip>000000000</cusip><assetCat>DBT</assetCat>"
        '<issuerConditional issuerCat="OTHER" desc="x"/>'
        "<debtSec><isDefault>Y</isDefault></debtSec></invstOrSec>"
        "</invstOrSecs></formData></edgarSubmission>"
    ).encode()


def xml_header(sub_type: str = "NPORT-P", cik: str = "0000000101", filing_date: str | None = None
               ) -> sa.AcceptanceHeader:
    accession = "0000000101-26-000009"
    filed = "" if filing_date is None else f"<FILING-DATE>{filing_date}\n"
    doc = (f"<SEC-HEADER>\n<ACCEPTANCE-DATETIME>20260812101500\n<ACCESSION-NUMBER>{accession}\n<TYPE>{sub_type}\n"
           f"{filed}<CIK>{cik}\n</SEC-HEADER>").encode()
    return sa.parse_acceptance_header(doc, accession_number=accession, url="u", document_sha256="0" * 64,
                                      retrieved_at=RETRIEVED)


def xml_twin_dera(tmp_path: Path, *, is_default: str = "Y") -> nport.DeraPackageResult:
    """DERA copy of ``xml_doc()`` in DERA lexical form (DD-MON-YYYY dates, trimmed decimals)."""
    twin = b.Filing("0000000101-26-000009", cik="0000000101", series="S000000001", report_date="30-JUN-2026",
                    filing_date="12-AUG-2026")
    twin.hold(1, CUSIP_A, is_default=is_default, arrears=None, pik=None, isins=["US0378331005"], name="Synthetic",
              title="NOTE", balance="1000.00", value="990", maturity="15-JAN-2030", rate="5")
    return run(tmp_path, [twin], label="2026q3_nport.zip")


def test_semantic_identity_normalizes_lexical_forms() -> None:
    dera = {"maturity_date_raw": "15-JAN-2030", "annualized_rate_raw": "5", "balance_raw": "1000"}
    xml = {"maturity_date_raw": "2030-01-15", "annualized_rate_raw": "5.000000000000", "balance_raw": "1000.00000000"}
    base = {name: None for name in nport.SEMANTIC_FIELDS}
    assert nport.semantic_sha({**base, **dera}) == nport.semantic_sha({**base, **xml})
    assert nport.semantic_sha({**base, **dera}) != nport.semantic_sha({**base, **dera, "balance_raw": "1000.5"})
    assert nport.canonical_decimal("-0.000") == "0" and nport.canonical_decimal("1E+3") == "1000"
    assert nport.canonical_decimal("N/A") == "raw:N/A"


def test_xml_to_dera_replay_is_one_semantic_lot_with_two_attestations(tmp_path: Path) -> None:
    dera = xml_twin_dera(tmp_path)
    xml = nport.parse_public_accession(xml_doc(), header=xml_header(filing_date="20260812"), retrieved_at=RETRIEVED,
                                       official_url="u")
    dera_obs = [o for o in observations(dera) if o.cusip9 == CUSIP_A]
    (xml_obs,) = xml.observations
    (dera_one,) = dera_obs
    assert dera_one.semantic_key == xml_obs.semantic_key  # raw lexical forms differ
    assert dera_one.observation_id != xml_obs.observation_id
    filings = nport.accession_filings_from_result(dera) + [nport.accession_filing_from_public(xml)]
    res = nport.resolve_accession_revisions(filings, knowledge_cutoff=K)
    assert res.copy_conflict_accessions == ()
    assert res.families[0].status == "selected" and len(res.attestations["0000000101-26-000009"]) == 2
    (vote,) = nport.build_votes(dera_obs + [xml_obs], resolution=res).votes
    assert vote.y_lots == 1 and len(vote.observation_ids) == 2


def test_changed_dera_copy_is_a_revision_conflict(tmp_path: Path) -> None:
    dera = xml_twin_dera(tmp_path, is_default="N")
    xml = nport.parse_public_accession(xml_doc(), header=xml_header(filing_date="20260812"), retrieved_at=RETRIEVED,
                                       official_url="u")
    filings = nport.accession_filings_from_result(dera) + [nport.accession_filing_from_public(xml)]
    res = nport.resolve_accession_revisions(filings, knowledge_cutoff=K)
    assert res.copy_conflict_accessions == ("0000000101-26-000009",)


def test_public_xml_parses_into_same_observation_contract() -> None:
    result = nport.parse_public_accession(xml_doc(), header=xml_header(), retrieved_at=RETRIEVED,
                                          official_url="https://www.sec.gov/x/primary_doc.xml")
    assert result.status == "parsed", result.quarantine_reasons
    assert result.source_package.source_family == "sec_nport_public_xml"
    (obs,) = result.observations
    assert obs.cusip9 == CUSIP_A and obs.report_date == dt.date(2026, 6, 30)
    assert obs.field_presence == {"nport_arrears_or_deferral": "null", "nport_is_default": "present",
                                  "nport_paid_in_kind": "absent"}
    assert obs.public_time_basis == "edgar_acceptance_datetime"
    assert obs.public_available_at == dt.datetime(2026, 8, 12, 14, 15, tzinfo=UTC)
    assert result.stats["excluded_not_corp_dbt"] == 1


@pytest.mark.parametrize(
    ("doc", "reason"),
    [
        (xml_doc(prefix='<!DOCTYPE x [<!ENTITY a "b">]>'), "xml_dtd_or_entity_declaration_refused"),
        (xml_doc(namespace="http://example.com/other"), "xml_root_unknown"),
        (xml_doc(sub_type="NPORT-NP"), "submission_type_not_public_nport"),
        (xml_doc(cik="0000000999"), "registrant_not_header_filer"),
        (b"<edgarSubmission", "xml_malformed"),
    ],
)
def test_public_xml_quarantine(doc: bytes, reason: str) -> None:
    result = nport.parse_public_accession(doc, header=xml_header(), retrieved_at=RETRIEVED, official_url="u")
    assert result.status == "quarantined" and not result.observations
    assert any(reason in r for r in result.quarantine_reasons), result.quarantine_reasons


def test_official_public_xml_sample() -> None:
    """Real public NPORT-P primary_doc.xml (0001145549-21-019739), cross-checked in the W1 smoke
    against the 2021q1 DERA rows of the same accession (16 CORP+DBT rows, identical CUSIPs/flags)."""
    import hashlib

    fixtures = ROOT / "tests" / "fixtures" / "bond_default_events"
    xml = (fixtures / "nport" / "0001145549-21-019739-primary_doc.xml").read_bytes()
    raw_header = (fixtures / "edgar" / "0001145549-21-019739-index-headers.html").read_bytes()
    assert hashlib.sha256(xml).hexdigest() == "d16ece5b8721cc4c139153e8c916072eb17dfcee6cf67e6986d8b12af2032d97"
    header = sa.parse_acceptance_header(raw_header, accession_number="0001145549-21-019739", url="u",
                                        document_sha256=hashlib.sha256(raw_header).hexdigest(),
                                        retrieved_at=RETRIEVED)
    result = nport.parse_public_accession(xml, header=header, retrieved_at=RETRIEVED, official_url="u")
    assert result.status == "parsed", result.quarantine_reasons
    assert result.stats["holdings"] == 63 and len(result.observations) == 16
    assert result.stats["excluded_not_corp_dbt"] == 47
    for obs in result.observations:
        assert set(obs.field_presence.values()) == {"present"}
        assert obs.public_time_basis == "edgar_acceptance_datetime"
        assert obs.public_available_at == dt.datetime(2021, 3, 31, 16, 0, 20, tzinfo=UTC)
    # The fund reports CUSIP "N/A" plus a custodian "other" identifier: never promoted to CUSIP9.
    assert {(o.cusip_raw, o.cusip9, o.isin_raw) for o in result.observations} == {("N/A", None, None)}


def test_xml_encoding_other_than_utf8_refused() -> None:
    with pytest.raises(nport.XmlSafetyError):
        nport.safe_xml_root(b'<?xml version="1.0" encoding="UTF-16"?><a/>')


_ENTITY_DOC = '<!DOCTYPE a [<!ENTITY x "INJECTED">]><a><b>&x;</b></a>'
_LAUGHS = (
    '<?xml version="1.0"?><!DOCTYPE l [<!ENTITY a "lol"><!ENTITY b "&a;&a;&a;&a;&a;&a;&a;&a;">'
    '<!ENTITY c "&b;&b;&b;&b;&b;&b;&b;&b;">]><l>&c;</l>'
)
_EXTERNAL = '<?xml version="1.0"?><!DOCTYPE a [<!ENTITY e SYSTEM "file:///etc/passwd">]><a>&e;</a>'


@pytest.mark.parametrize(
    "payload",
    [
        _ENTITY_DOC.encode("utf-16-le"),  # BOM-less UTF-16LE: DTD regex on bytes cannot see it
        _ENTITY_DOC.encode("utf-16-be"),
        _ENTITY_DOC.encode("utf-32-le"),
        "<a><b>x</b></a>".encode("utf-16-le"),  # even without a DTD: encoding not permitted
        _LAUGHS.encode(),
        _EXTERNAL.encode(),
        b"\xef\xbb\xbf" + _ENTITY_DOC.encode(),  # UTF-8 BOM does not bypass the DTD rule
        b'<?xml version="1.0" encoding="ISO-8859-1"?><a>\xe9</a>',
        b"<a>\xff\xfe</a>",  # invalid UTF-8
        b'<!DOCTYPE a SYSTEM "http://example.com/a.dtd"><a/>',
    ],
)
def test_xml_dtd_entities_and_non_utf8_refused_before_parsing(payload: bytes) -> None:
    with pytest.raises(nport.XmlSafetyError):
        nport.safe_xml_root(payload)


def test_xml_utf8_with_or_without_bom_accepted() -> None:
    for payload in (b"<a><b>ok</b></a>", b"\xef\xbb\xbf<?xml version=\"1.0\" encoding=\"UTF-8\"?><a><b>ok</b></a>"):
        assert nport.safe_xml_root(payload).find("b").text == "ok"


@pytest.mark.parametrize(
    ("old", "new"),
    [
        # foreign-namespace credit flag nested in debtSec (must not be read as C.9.c)
        ("<isDefault>Y</isDefault>", '<x:isDefault xmlns:x="http://example.com/evil">Y</x:isDefault>'),
        # no-namespace element with the mapped local name
        ("<isDefault>Y</isDefault>", '<isDefault xmlns="">Y</isDefault>'),
        # foreign-namespace copy next to the official one
        ("<isDefault>Y</isDefault>", '<isDefault>N</isDefault><x:isDefault xmlns:x="urn:x">Y</x:isDefault>'),
        # wrong namespace on required filing-level fields and on the debt container
        ("<repPdDate>2026-06-30</repPdDate>", '<repPdDate xmlns="urn:x">2026-06-30</repPdDate>'),
        ("<debtSec>", '<debtSec xmlns="urn:x">'),
        ("<cusip>", '<c:cusip xmlns:c="http://www.sec.gov/edgar/common">'),
    ],
)
def test_public_xml_wrong_namespace_quarantines_filing(old: str, new: str) -> None:
    doc = xml_doc().decode()
    assert old in doc
    if new.startswith("<c:cusip"):
        doc = doc.replace(f"<cusip>{CUSIP_A}</cusip>", f"{new}{CUSIP_A}</c:cusip>")
    elif new.startswith('<debtSec xmlns="urn:x">'):
        doc = doc.replace(old, new, 1)
    else:
        doc = doc.replace(old, new, 1)
    result = nport.parse_public_accession(doc.encode(), header=xml_header(), retrieved_at=RETRIEVED,
                                          official_url="u")
    assert result.status == "quarantined", result.stats
    assert not result.observations
    assert any(r.startswith("xml_namespace_mismatch") for r in result.quarantine_reasons), result.quarantine_reasons


def test_public_xml_unrelated_foreign_extension_ignored() -> None:
    doc = xml_doc().decode().replace("<title>NOTE</title>", '<title>NOTE</title><x:note xmlns:x="urn:x">hi</x:note>')
    result = nport.parse_public_accession(doc.encode(), header=xml_header(), retrieved_at=RETRIEVED,
                                          official_url="u")
    assert result.status == "parsed" and len(result.observations) == 1


def test_public_accession_rejects_utf16_entity_bypass() -> None:
    doc = xml_doc().decode().replace('<?xml version="1.0" encoding="UTF-8"?>', "")
    doc = '<!DOCTYPE edgarSubmission [<!ENTITY y "Y">]>' + doc.replace("<isDefault>Y</isDefault>",
                                                                      "<isDefault>&y;</isDefault>")
    result = nport.parse_public_accession(doc.encode("utf-16-le"), header=xml_header(), retrieved_at=RETRIEVED,
                                          official_url="u")
    assert result.status == "quarantined" and not result.observations


# --- accession revisions ------------------------------------------------------------
def af(accession: str, *, sub: str = "NPORT-P", filed: dt.date = dt.date(2021, 5, 20), holdings: int = 10,
       at: dt.datetime = RETRIEVED, basis: str = "first_verified_retrieval", digest: str = "d", package: str = "p1",
       report: dt.date = dt.date(2021, 3, 31)) -> nport.AccessionFiling:
    return nport.AccessionFiling(accession, "0000000101", "S000000001", report, sub, filed, at, basis, holdings,
                                 digest, package, retrieved_at=at)


def reference_build_votes(
    rows: Iterable[c.CreditObservation], *, resolution: nport.RevisionResolution
) -> nport.VoteSet:
    """Pre-Stage-2 vote body, retained only as an output-identity oracle."""
    status = resolution.accession_status()
    cutoff = resolution.knowledge_cutoff
    excluded: Counter[str] = Counter()
    lots: dict[nport.VoteKey, dict[str, list[c.CreditObservation]]] = defaultdict(lambda: defaultdict(list))
    registrants: dict[nport.VoteKey, str | None] = {}
    for observation in rows:
        if observation.observation_kind != "nport_holding":
            excluded["not_nport_holding"] += 1
            continue
        if observation.public_available_at > cutoff:
            excluded["observation_after_cutoff"] += 1
            continue
        if resolution.mode == "current_run" and observation.first_seen_at > cutoff:
            excluded["observation_not_ingested_by_cutoff"] += 1
            continue
        if observation.cusip9 is None:
            excluded["cusip9_unlinked"] += 1
            continue
        accession = observation.accession_number or ""
        state = status.get(accession, "not_in_resolution")
        if state != "selected":
            excluded[f"accession_{state}"] += 1
            continue
        if str(observation.package_id) not in resolution.attestations.get(accession, ()):
            excluded["package_copy_not_eligible_at_cutoff"] += 1
            continue
        fund = nport.fund_key_for(observation.series_id, observation.registrant_cik)
        if fund is None or observation.report_date is None:
            excluded["fund_or_report_date_missing"] += 1
            continue
        key = (accession, fund, observation.cusip9, observation.report_date)
        lots[key][observation.semantic_key].append(observation)
        registrants[key] = observation.registrant_cik
    votes: list[nport.Vote] = []
    for key in sorted(lots, key=lambda k: (k[2], k[3], k[1], k[0])):
        semantic = lots[key]
        y = n = none = invalid = 0
        arrears = pik = False
        ids: list[uuid.UUID] = []
        y_ids: list[uuid.UUID] = []
        n_ids: list[uuid.UUID] = []
        known: list[dt.datetime] = []
        for copies in semantic.values():
            first = copies[0]
            copy_ids = [copy.observation_id for copy in copies]
            ids.extend(copy_ids)
            known.append(min(copy.public_available_at for copy in copies))
            presence = first.field_presence["nport_is_default"]
            if presence == "present" and first.nport_is_default == "Y":
                y += 1
                y_ids.extend(copy_ids)
            elif presence == "present" and first.nport_is_default == "N":
                n += 1
                n_ids.extend(copy_ids)
            else:
                none += 1
                invalid += presence == "invalid"
            arrears = arrears or first.nport_arrears_or_deferral == "Y"
            pik = pik or first.nport_paid_in_kind == "Y"
        value = "disputed" if y and n else "Y" if y else "N" if n else "none"
        votes.append(
            nport.Vote(
                accession_number=key[0], fund_key=key[1], registrant_cik=registrants[key], cusip9=key[2],
                report_date=key[3], value=value, y_lots=y, n_lots=n, nonvote_lots=none, invalid_lots=invalid,
                arrears_or_deferral_y=arrears, paid_in_kind_y=pik,
                observation_ids=tuple(sorted(ids, key=str)), y_observation_ids=tuple(sorted(y_ids, key=str)),
                n_observation_ids=tuple(sorted(n_ids, key=str)), public_available_at=max(known),
            )
        )
    disputed = tuple(family for family in resolution.families if family.status == "disputed")
    return nport.VoteSet(tuple(votes), dict(sorted(excluded.items())), disputed)


def test_amended_complete_replacement_selected() -> None:
    res = nport.resolve_accession_revisions(
        [af("A-1"), af("A-2", sub="NPORT-P/A", filed=dt.date(2021, 6, 2))], knowledge_cutoff=K)
    (family,) = res.families
    assert family.status == "selected" and family.selected_accession == "A-2"
    assert family.superseded_accessions == ("A-1",) and family.ordering_basis == "filing_date"


def test_ambiguous_partial_amendment_disputed() -> None:
    res = nport.resolve_accession_revisions(
        [af("A-1"), af("A-2", sub="NPORT-P/A", filed=dt.date(2021, 6, 2), holdings=0)], knowledge_cutoff=K)
    assert res.families[0].status == "disputed"
    assert "ambiguous_partial_amendment" in res.families[0].reasons


def test_late_amendment_preserves_prior_cutoff_facts() -> None:
    late = dt.datetime(2026, 11, 1, tzinfo=UTC)
    members = [af("A-1"), af("A-2", sub="NPORT-P/A", filed=dt.date(2026, 11, 1), at=late)]
    early = nport.resolve_accession_revisions(members, knowledge_cutoff=K)
    assert early.families[0].selected_accession == "A-1" and early.families[0].after_cutoff_accessions == ("A-2",)
    later = nport.resolve_accession_revisions(members, knowledge_cutoff=dt.datetime(2026, 12, 1, tzinfo=UTC))
    assert later.families[0].selected_accession == "A-2"


def test_multiple_originals_and_unordered_revisions_disputed() -> None:
    res = nport.resolve_accession_revisions([af("A-1"), af("A-2", filed=dt.date(2021, 5, 21))], knowledge_cutoff=K)
    assert res.families[0].status == "disputed" and "multiple_originals" in res.families[0].reasons
    same_day = [af("A-1"), af("A-2", sub="NPORT-P/A")]
    res = nport.resolve_accession_revisions(same_day, knowledge_cutoff=K)
    assert "revision_order_ambiguous" in res.families[0].reasons
    t1, t2 = dt.datetime(2021, 5, 20, 14, tzinfo=UTC), dt.datetime(2021, 5, 20, 15, tzinfo=UTC)
    ordered = [af("A-1", at=t1, basis="edgar_acceptance_datetime"),
               af("A-2", sub="NPORT-P/A", at=t2, basis="edgar_acceptance_datetime")]
    res = nport.resolve_accession_revisions(ordered, knowledge_cutoff=K)
    assert res.families[0].selected_accession == "A-2" and res.families[0].ordering_basis == "edgar_acceptance"


def test_amendment_before_original_disputed() -> None:
    res = nport.resolve_accession_revisions(
        [af("A-1", filed=dt.date(2021, 6, 2)), af("A-2", sub="NPORT-P/A")], knowledge_cutoff=K)
    assert "original_after_amendment" in res.families[0].reasons


def test_accession_copies_across_packages() -> None:
    same = nport.resolve_accession_revisions([af("A-1", package="p1"), af("A-1", package="p2")], knowledge_cutoff=K)
    assert same.families[0].selected_accession == "A-1" and same.attestations["A-1"] == ("p1", "p2")
    conflicting = nport.resolve_accession_revisions(
        [af("A-1", package="p1"), af("A-1", package="p2", digest="other")], knowledge_cutoff=K)
    assert conflicting.families[0].status == "disputed"
    assert conflicting.copy_conflict_accessions == ("A-1",)


def test_repeated_accession_across_packages_is_one_vote(tmp_path: Path) -> None:
    def make() -> list:
        return [filing(1).hold(1, CUSIP_A, is_default="Y").hold(2, CUSIP_A, is_default="Y")]

    first = run(tmp_path, make(), label="2021q1_nport.zip")
    second = run(tmp_path, make(), label="2021q2_nport.zip")
    obs = observations(first) + observations(second)
    filings = nport.accession_filings_from_result(first) + nport.accession_filings_from_result(second)
    res = nport.resolve_accession_revisions(filings, knowledge_cutoff=K)
    votes = nport.build_votes(obs, resolution=res).votes
    (vote,) = votes
    # One vote; the two lots stay two lots, the two package copies of each lot collapse.
    assert vote.value == "Y" and vote.y_lots == 2
    assert len(vote.observation_ids) == 4 and vote.report_date == dt.date(2021, 3, 31)
    assert len({o.semantic_key for o in obs}) == 2 and len({o.observation_id for o in obs}) == 4


LATER = K + dt.timedelta(days=30)


def test_later_changed_copy_of_same_accession_cannot_alter_prior_k(tmp_path: Path) -> None:
    before = af("A-1", package="p1")
    after = af("A-1", package="p2", digest="changed", at=LATER)
    prior = nport.resolve_accession_revisions([before, after], knowledge_cutoff=K)
    (family,) = prior.families
    assert family.status == "selected" and family.selected_accession == "A-1"
    assert prior.copy_conflict_accessions == () and prior.attestations["A-1"] == ("p1",)
    assert prior.after_cutoff_copies == {"A-1": ("p2",)}
    later = nport.resolve_accession_revisions([before, after], knowledge_cutoff=LATER)
    assert later.families[0].status == "disputed" and later.copy_conflict_accessions == ("A-1",)


def test_votes_exclude_post_k_observations_on_selected_accession(tmp_path: Path) -> None:
    first = run(tmp_path, [filing(1).hold(1, CUSIP_A, is_default="N")], label="2021q1_nport.zip")
    changed = run(tmp_path, [filing(1).hold(1, CUSIP_A, is_default="Y")], label="2021q2_nport.zip",
                  retrieved=LATER)
    filings = nport.accession_filings_from_result(first) + nport.accession_filings_from_result(changed)
    obs = observations(first) + observations(changed)
    res = nport.resolve_accession_revisions(filings, knowledge_cutoff=K)
    voteset = nport.build_votes(obs, resolution=res)
    (vote,) = voteset.votes
    assert vote.value == "N" and vote.y_lots == 0
    assert voteset.excluded_observations == {"observation_after_cutoff": 1}


def test_current_run_mode_requires_ingestion_by_cutoff(tmp_path: Path) -> None:
    result = run(tmp_path, [filing(1).hold(1, CUSIP_A, is_default="Y")])
    filings = nport.accession_filings_from_result(result)
    late_seen = list(nport.iter_package_observations(result, first_seen_at=LATER))
    historical = nport.resolve_accession_revisions(filings, knowledge_cutoff=K)
    assert len(nport.build_votes(late_seen, resolution=historical).votes) == 1
    current = nport.resolve_accession_revisions(filings, knowledge_cutoff=K, mode="current_run")
    voteset = nport.build_votes(late_seen, resolution=current)
    assert voteset.votes == () and voteset.excluded_observations == {"observation_not_ingested_by_cutoff": 1}
    retrieved_late = [dataclasses.replace(f, retrieved_at=LATER) for f in filings]
    unavailable = nport.resolve_accession_revisions(retrieved_late, knowledge_cutoff=K, mode="current_run")
    assert unavailable.families[0].status == "unavailable"


def test_amendment_rows_never_blended_with_original(tmp_path: Path) -> None:
    original = b.Filing("0000000001-21-000001", cik="0000000101", series="S000000001").hold(1, CUSIP_A, is_default="Y")
    amendment = b.Filing("0000000001-21-000002", cik="0000000101", series="S000000001", sub_type="NPORT-P/A",
                         filing_date="02-JUN-2021").hold(2, CUSIP_A, is_default="N")
    result = run(tmp_path, [original, amendment])
    res = nport.resolve_accession_revisions(nport.accession_filings_from_result(result), knowledge_cutoff=K)
    voteset = nport.build_votes(observations(result), resolution=res)
    (vote,) = voteset.votes
    assert vote.accession_number == "0000000001-21-000002" and vote.value == "N"
    assert voteset.excluded_observations == {"accession_superseded": 1}


def test_prepared_vote_builder_matches_reference_and_isolation(tmp_path: Path) -> None:
    package = run(
        tmp_path,
        [filing(1).hold(1, CUSIP_A, is_default="Y").hold(2, CUSIP_A, is_default="N")
         .hold(3, CUSIP_B, is_default=None).hold(4, CUSIP_B, is_default="invalid")],
    )
    source = observations(package)
    assert package.source_package is not None
    package_id = str(package.source_package.package_id)
    copy_id = uuid.uuid5(uuid.NAMESPACE_URL, "prepared-vote-copy")
    t1 = dt.datetime(2021, 5, 20, 14, tzinfo=UTC)
    t2 = dt.datetime(2021, 6, 2, 14, tzinfo=UTC)
    unplaceable = dataclasses.replace(
        af("UNPLACEABLE", package=package_id, report=dt.date(2021, 6, 30)),
        registrant_cik=None,
        fund_key=None,
        report_date=None,
    )
    filings = [
        af("SELECTED", package=package_id),
        af("SELECTED", package=str(copy_id)),
        af("OLD", package=package_id, report=dt.date(2021, 4, 30), at=t1, basis="edgar_acceptance_datetime"),
        af("NEW", package=package_id, report=dt.date(2021, 4, 30), sub="NPORT-P/A",
           filed=dt.date(2021, 6, 2), at=t2, basis="edgar_acceptance_datetime"),
        af("DISPUTED-1", package=package_id, report=dt.date(2021, 5, 31)),
        af("DISPUTED-2", package=package_id, report=dt.date(2021, 5, 31), filed=dt.date(2021, 5, 21)),
        unplaceable,
        af("AFTER-K", package=package_id, report=dt.date(2021, 7, 31), at=LATER),
    ]
    historical = nport.resolve_accession_revisions(filings, knowledge_cutoff=K)
    current = nport.resolve_accession_revisions(filings, knowledge_cutoff=K, mode="current_run")
    selected = [dataclasses.replace(row, accession_number="SELECTED") for row in source]
    selected.append(dataclasses.replace(
        selected[0], package_id=copy_id,
        observation_id=c.CreditObservation.derive_id(copy_id, selected[0].member_name, selected[0].row_locator),
    ))
    ineligible_copy_id = uuid.uuid4()
    excluded = [
        dataclasses.replace(source[0], public_available_at=LATER, first_seen_at=LATER),
        dataclasses.replace(source[0], cusip9=None),
        dataclasses.replace(source[0], accession_number="UNKNOWN"),
        dataclasses.replace(
            source[0], accession_number="SELECTED", package_id=ineligible_copy_id,
            observation_id=c.CreditObservation.derive_id(
                ineligible_copy_id, source[0].member_name, source[0].row_locator
            ),
        ),
        dataclasses.replace(source[0], accession_number="SELECTED", registrant_cik=None, series_id=None),
        dataclasses.replace(source[0], accession_number="OLD"),
        dataclasses.replace(source[0], accession_number="DISPUTED-1"),
        dataclasses.replace(source[0], accession_number="UNPLACEABLE"),
        dataclasses.replace(source[0], accession_number="AFTER-K"),
    ]
    late_seen = dataclasses.replace(selected[0], first_seen_at=LATER)
    rows = [*selected, *excluded]

    historical_builder = nport._PreparedVoteBuilder(historical)
    assert historical_builder.build(rows) == reference_build_votes(rows, resolution=historical)
    assert historical_builder.build([]) == reference_build_votes([], resolution=historical)
    assert nport._PreparedVoteBuilder(current).build([late_seen]) == reference_build_votes(
        [late_seen], resolution=current
    )
    public_status = historical.accession_status()
    public_status["SELECTED"] = "disputed_family"
    assert historical.accession_status()["SELECTED"] == "selected"
    assert historical_builder.build(selected) == reference_build_votes(selected, resolution=historical)
    with pytest.raises(TypeError):
        historical_builder._accession_status["SELECTED"] = "superseded"

    changed_copy = af("SAME", package="late", digest="changed", at=LATER)
    early = nport.resolve_accession_revisions([af("SAME", package=package_id), changed_copy], knowledge_cutoff=K)
    late = nport.resolve_accession_revisions([af("SAME", package=package_id), changed_copy], knowledge_cutoff=LATER)
    same = dataclasses.replace(source[0], accession_number="SAME")
    assert len(nport._PreparedVoteBuilder(early).build([same]).votes) == 1
    assert nport._PreparedVoteBuilder(late).build([same]).votes == ()


def test_public_build_votes_prepares_once_per_call(monkeypatch: pytest.MonkeyPatch) -> None:
    resolution = nport.resolve_accession_revisions([], knowledge_cutoff=K)
    original = nport.RevisionResolution.accession_status
    calls = 0

    def counted(self: nport.RevisionResolution) -> dict[str, str]:
        nonlocal calls
        calls += 1
        return original(self)

    monkeypatch.setattr(nport.RevisionResolution, "accession_status", counted)
    assert nport.build_votes([], resolution=resolution) == nport.VoteSet((), {}, ())
    assert calls == 1


# --- votes and consensus --------------------------------------------------------------
def vote(fund: str, cik: str, value: str, *, cusip: str = CUSIP_A, day: dt.date = dt.date(2021, 3, 31),
         arrears: bool = False, pik: bool = False, accession: str | None = None) -> nport.Vote:
    if len(fund) == 2 and fund[0] == "S" and fund[1].isdigit():  # shorthand "S1" -> "S000000001"
        fund = f"S{int(fund[1]):09d}"
    oid = uuid.uuid5(uuid.NAMESPACE_URL, f"{fund}{cik}{value}{cusip}{day}")
    return nport.Vote(
        accession_number=accession or f"acc-{fund}-{day}", fund_key=fund, registrant_cik=cik, cusip9=cusip,
        report_date=day, value=value, y_lots=value in ("Y", "disputed"), n_lots=value in ("N", "disputed"),
        nonvote_lots=value == "none", invalid_lots=0, arrears_or_deferral_y=arrears, paid_in_kind_y=pik,
        observation_ids=(oid,), y_observation_ids=(oid,) if value in ("Y", "disputed") else (),
        n_observation_ids=(oid,) if value in ("N", "disputed") else (), public_available_at=RETRIEVED,
    )


EARLY = dt.datetime(2021, 1, 1, tzinfo=UTC)


def fam(cik: str, family: str, *, known_at: dt.datetime = EARLY, public_at: dt.datetime = EARLY,
        valid_from: dt.date | None = None, valid_to: dt.date | None = None) -> nport.FamilyEvidence:
    return nport.FamilyEvidence(
        registrant_cik=cik, family_id=family, evidence_ref=f"ncen:{cik}:{family}",
        evidence_digest="sha256:" + hashlib.sha256(f"{cik}{family}".encode()).hexdigest(),
        valid_from=valid_from, valid_to=valid_to, public_available_at=public_at, known_at=known_at,
    )


def corroboration(economic: dt.date = dt.date(2021, 3, 1), *, public_at: dt.datetime = EARLY,
                  link_at: dt.datetime = EARLY, adjudicated_at: dt.datetime = EARLY,
                  source: str = "sec_edgar") -> nport.IndependentCorroboration:
    return nport.IndependentCorroboration(
        cusip9=CUSIP_A, source_kind=source, default_evidenced_by=economic,
        evidence_observation_ids=(uuid.uuid5(uuid.NAMESPACE_URL, f"corr-obs-{economic}-{source}"),),
        adjudication_id=uuid.uuid5(uuid.NAMESPACE_URL, f"corr-adj-{economic}-{source}"),
        evidence_refs=(f"edgar:0000000999-21-000001:{source}",), evidence_digests=("sha256:" + "c" * 64,),
        evidence_public_at=public_at, link_known_at=link_at, adjudication_known_at=adjudicated_at,
    )


FAMILIES = {
    "0000000101": fam("0000000101", "family-a"),
    "0000000102": fam("0000000102", "family-b"),
    "0000000103": fam("0000000103", "family-a"),
}


def consensus(votes, **kwargs) -> nport.ConsensusResult:
    kwargs.setdefault("knowledge_cutoff", K)
    return nport.build_consensus_states(votes, **kwargs)


def state(result: nport.ConsensusResult, day: dt.date = dt.date(2021, 3, 31)) -> nport.DateState:
    return next(s for s in result.date_states if s.report_date == day)


def test_two_families_versus_same_family_series() -> None:
    two = consensus([vote("S1", "0000000101", "Y"), vote("S2", "0000000102", "Y")], family_evidence=FAMILIES)
    assert (state(two).status, state(two).basis) == ("consensus_y", "independent_families")
    same = consensus([vote("S1", "0000000101", "Y"), vote("S3", "0000000103", "Y")], family_evidence=FAMILIES)
    assert (state(same).status, state(same).basis) == ("candidate_y", "same_family_uncorroborated")
    corroborated = consensus([vote("S1", "0000000101", "Y"), vote("S3", "0000000103", "Y")],
                             family_evidence=FAMILIES, corroborations=[corroboration()])
    assert (state(corroborated).status, state(corroborated).basis) == ("consensus_y", "same_family_corroborated")
    too_late = consensus([vote("S1", "0000000101", "Y"), vote("S3", "0000000103", "Y")], family_evidence=FAMILIES,
                         corroborations=[corroboration(dt.date(2021, 6, 1), source="agency_rocr")])
    assert state(too_late).status == "candidate_y"


def test_late_disclosed_corroboration_of_earlier_economic_event() -> None:
    """Economic event (2021-03-01) precedes the report date, but its evidence became public after K."""
    votes = [vote("S1", "0000000101", "Y"), vote("S3", "0000000103", "Y")]
    late = K + dt.timedelta(days=10)
    for kwargs in ({"public_at": late}, {"link_at": late}, {"adjudicated_at": late}):
        at_k = consensus(votes, family_evidence=FAMILIES, corroborations=[corroboration(**kwargs)])
        assert state(at_k).status == "candidate_y" and not at_k.proposals[0].corroboration_adjudication_ids
        assert at_k.stats["corroborations_unavailable_at_cutoff"] == 1
    later = consensus(votes, family_evidence=FAMILIES, corroborations=[corroboration(public_at=late)],
                      knowledge_cutoff=late)
    (proposal,) = later.proposals
    assert proposal.proposed_status == "accepted_state" and proposal.evidence_known_at == late


def test_late_known_family_mapping() -> None:
    votes = [vote("S1", "0000000101", "Y"), vote("S2", "0000000102", "Y")]
    late = K + dt.timedelta(days=3)
    families = {**FAMILIES, "0000000102": fam("0000000102", "family-b", known_at=late)}
    at_k = consensus(votes, family_evidence=families)
    assert (state(at_k).status, state(at_k).basis) == ("candidate_y", "family_independence_unknown")
    after = consensus(votes, family_evidence=families, knowledge_cutoff=late)
    (proposal,) = after.proposals
    assert proposal.proposed_status == "accepted_state" and proposal.evidence_known_at == late
    assert {r.evidence_ref for r in proposal.family_evidence} == {"ncen:0000000101:family-a",
                                                                  "ncen:0000000102:family-b"}
    expired = {**FAMILIES, "0000000102": fam("0000000102", "family-b", valid_to=dt.date(2021, 1, 1))}
    assert state(consensus(votes, family_evidence=expired)).basis == "family_independence_unknown"
    conflicting = {**FAMILIES, "0000000102": [fam("0000000102", "family-b"), fam("0000000102", "family-c")]}
    assert state(consensus(votes, family_evidence=conflicting)).basis == "family_independence_unknown"


def test_proposal_carries_every_dependency() -> None:
    corr = corroboration()
    n_day = dt.date(2020, 12, 31)
    votes = [vote("S1", "0000000101", "N", day=n_day), vote("S2", "0000000102", "N", day=n_day),
             vote("S1", "0000000101", "Y"), vote("S3", "0000000103", "Y")]
    (proposal,) = consensus(votes, family_evidence=FAMILIES, corroborations=[corr]).proposals
    assert proposal.basis == "same_family_corroborated"
    assert set(corr.evidence_observation_ids) <= set(proposal.evidence_observation_ids)
    assert proposal.corroboration_adjudication_ids == (corr.adjudication_id,)
    assert proposal.corroboration_evidence_refs == corr.evidence_refs
    y_ids = {i for v in votes[2:] for i in v.y_observation_ids}
    n_ids = {i for v in votes[:2] for i in v.n_observation_ids}
    assert set(proposal.onset_upper_evidence_ids) == y_ids and set(proposal.onset_lower_evidence_ids) == n_ids
    assert (y_ids | n_ids) <= set(proposal.evidence_observation_ids)
    assert {r.registrant_cik for r in proposal.family_evidence} == {"0000000101", "0000000102", "0000000103"}
    assert proposal.evidence_known_at == RETRIEVED


def test_votes_after_cutoff_are_rejected_by_consensus() -> None:
    late_vote = dataclasses.replace(vote("S2", "0000000102", "Y"), public_available_at=K + dt.timedelta(hours=1))
    result = consensus([vote("S1", "0000000101", "Y"), late_vote], family_evidence=FAMILIES)
    assert state(result).basis == "single_series" and result.stats["votes_after_cutoff"] == 1


def test_cik_independence_unknown_cannot_support() -> None:
    result = consensus([vote("S1", "0000000101", "Y"), vote("S9", "0000000999", "Y")],
                                         family_evidence=FAMILIES)
    assert (state(result).status, state(result).basis) == ("candidate_y", "family_independence_unknown")
    assert consensus([vote("S1", "0000000101", "Y"), vote("S2", "0000000102", "Y")]
                                        ).date_states[0].status == "candidate_y"  # no evidence supplied


@pytest.mark.parametrize(("series_a", "series_b"), [(None, None), ("X000000001", "S00000002"), (None, "S000000002")])
def test_cik_fallback_fund_keys_never_count_as_series(tmp_path: Path, series_a, series_b) -> None:
    """Absent or malformed SERIES_ID falls back to a cik: grouping key that is not a series."""
    filings = [
        b.Filing("0000000001-21-000001", cik="0000000101", series=series_a).hold(1, CUSIP_A, is_default="Y"),
        b.Filing("0000000002-21-000001", cik="0000000102", series=series_b).hold(2, CUSIP_A, is_default="Y"),
    ]
    result = run(tmp_path, filings)
    res = nport.resolve_accession_revisions(nport.accession_filings_from_result(result), knowledge_cutoff=K)
    votes = nport.build_votes(observations(result), resolution=res).votes
    assert len(votes) == 2 and any(v.fund_key.startswith("cik:") for v in votes)
    outcome = consensus(votes, family_evidence=FAMILIES)
    assert state(outcome).status == "candidate_y"
    assert state(outcome).basis in ("series_id_missing", "single_series")
    assert all(p.proposed_status != "accepted_state" for p in outcome.proposals)


def test_single_y_stays_candidate() -> None:
    result = consensus([vote("S1", "0000000101", "Y")], family_evidence=FAMILIES)
    assert state(result).basis == "single_series"
    cik_only = consensus([vote("cik:0000000101", "0000000101", "Y"),
                                             vote("cik:0000000102", "0000000102", "Y")], family_evidence=FAMILIES)
    assert (state(cik_only).status, state(cik_only).basis) == ("candidate_y", "series_id_missing")
    (proposal,) = result.proposals
    assert proposal.proposed_status == "candidate" and proposal.onset_upper_inclusive is None


def test_material_conflicts_go_to_adjudication_never_majority() -> None:
    votes = [vote("S1", "0000000101", "Y"), vote("S2", "0000000102", "Y"), vote("S4", "0000000103", "Y"),
             vote("S5", "0000000999", "N")]
    result = consensus(votes, family_evidence=FAMILIES)
    assert (state(result).status, state(result).basis) == ("conflict", "material_y_n_conflict")
    assert not result.proposals
    assert [q.kind for q in result.adjudication_queue] == ["nport_state_conflict"]
    resolved = consensus(votes, family_evidence=FAMILIES, resolved_votes=[votes[3].key])
    assert state(resolved).status == "consensus_y"
    intra = consensus([vote("S1", "0000000101", "disputed"), vote("S2", "0000000102", "Y")],
                                        family_evidence=FAMILIES)
    assert (state(intra).status, state(intra).basis) == ("conflict", "contradictory_lots")


def test_duplicate_lots_are_one_vote_and_contradictory_lots_dispute(tmp_path: Path) -> None:
    f = filing(1).hold(1, CUSIP_A, is_default="Y", balance="10").hold(2, CUSIP_A, is_default="Y", balance="20")
    g = filing(2, cik="0000000102", series="S000000002").hold(3, CUSIP_A, is_default="Y").hold(
        4, CUSIP_A, is_default="N", balance="7")
    result = run(tmp_path, [f, g])
    res = nport.resolve_accession_revisions(nport.accession_filings_from_result(result), knowledge_cutoff=K)
    votes = {v.fund_key: v for v in nport.build_votes(observations(result), resolution=res).votes}
    assert votes["S000000001"].value == "Y" and votes["S000000001"].y_lots == 2
    assert votes["S000000002"].value == "disputed"


def test_first_y_without_prior_n_is_prevalent_left_censored() -> None:
    result = consensus([vote("S1", "0000000101", "Y"), vote("S2", "0000000102", "Y")],
                                         family_evidence=FAMILIES)
    (proposal,) = result.proposals
    assert proposal.proposed_status == "accepted_state" and proposal.reviewer_role == "policy_rule_engine"
    assert proposal.onset_lower_exclusive is None and proposal.onset_upper_inclusive == dt.date(2021, 3, 31)
    assert proposal.timing_class == "prevalent" and proposal.left_censored


@pytest.mark.parametrize(
    ("n_day", "timing"),
    [(dt.date(2020, 12, 31), "interval_uncertain"), (dt.date(2021, 3, 30), "incident")],
)
def test_onset_interval_from_last_credible_n(n_day: dt.date, timing: str) -> None:
    y_day = dt.date(2021, 3, 31)
    votes = [
        vote("S1", "0000000101", "N", day=dt.date(2020, 9, 30)), vote("S2", "0000000102", "N", day=dt.date(2020, 9, 30)),
        vote("S1", "0000000101", "N", day=n_day), vote("S2", "0000000102", "N", day=n_day),
        vote("S1", "0000000101", "Y", day=y_day), vote("S2", "0000000102", "Y", day=y_day),
    ]
    (proposal,) = consensus(votes, family_evidence=FAMILIES).proposals
    assert (proposal.onset_lower_exclusive, proposal.onset_upper_inclusive) == (n_day, y_day)
    assert proposal.timing_class == timing and not proposal.left_censored


def test_single_fund_n_is_not_a_credible_lower_bound() -> None:
    votes = [vote("S1", "0000000101", "N", day=dt.date(2021, 2, 28)),
             vote("S1", "0000000101", "Y"), vote("S2", "0000000102", "Y")]
    (proposal,) = consensus(votes, family_evidence=FAMILIES).proposals
    assert proposal.onset_lower_exclusive is None and proposal.timing_class == "prevalent"


def test_false_cure_n_after_y_is_one_episode_and_queued() -> None:
    days = [dt.date(2021, 3, 31), dt.date(2021, 6, 30), dt.date(2021, 9, 30)]
    votes = [vote("S1", "0000000101", "Y", day=days[0]), vote("S2", "0000000102", "Y", day=days[0]),
             vote("S1", "0000000101", "N", day=days[1]), vote("S2", "0000000102", "N", day=days[1]),
             vote("S1", "0000000101", "Y", day=days[2]), vote("S2", "0000000102", "Y", day=days[2])]
    result = consensus(votes, family_evidence=FAMILIES)
    (proposal,) = result.proposals
    assert proposal.onset_upper_inclusive == days[0]
    assert proposal.credible_n_after_first_y == (days[1],) and proposal.subsequent_y_dates == (days[2],)
    assert [q.kind for q in result.adjudication_queue] == ["nport_credible_n_after_y"]


def test_arrears_deferral_and_pik_never_default() -> None:
    votes = [vote("S1", "0000000101", "N", arrears=True, pik=True), vote("S2", "0000000102", "N", arrears=True)]
    result = consensus(votes, family_evidence=FAMILIES)
    assert state(result).status == "consensus_n" and state(result).arrears_or_legal_deferral_unknown
    assert not result.proposals


def test_disputed_families_are_queued() -> None:
    family = nport.FilingFamily("0000000101", "S1", dt.date(2021, 3, 31), "disputed", None, ("A-1", "A-2"), (),
                                "ambiguous", ("revision_order_ambiguous",))
    result = consensus([], disputed_families=[family])
    (item,) = result.adjudication_queue
    assert item.kind == "nport_filing_family_disputed" and item.accessions == ("A-1", "A-2")


def test_corroboration_source_must_be_edgar_or_agency() -> None:
    bad = corroboration(source="market_price")
    with pytest.raises(nport.NportError):
        consensus([], corroborations=[bad])


def test_end_to_end_package_to_state_proposal(tmp_path: Path) -> None:
    prior = [b.Filing(f"00000000{i}1-20-000001", cik=cik, series=s, report_date="31-DEC-2020",
                      filing_date="25-FEB-2021").hold(i, CUSIP_A, is_default="N")
             for i, cik, s in ((1, "0000000101", "S000000001"), (2, "0000000102", "S000000002"))]
    current = [b.Filing(f"00000000{i}2-21-000001", cik=cik, series=s).hold(i + 10, CUSIP_A, is_default="Y")
               for i, cik, s in ((1, "0000000101", "S000000001"), (2, "0000000102", "S000000002"))]
    result = run(tmp_path, prior + current)
    res = nport.resolve_accession_revisions(nport.accession_filings_from_result(result), knowledge_cutoff=K)
    votes = nport.build_votes(observations(result), resolution=res).votes
    (proposal,) = consensus(votes, family_evidence=FAMILIES).proposals
    assert (proposal.onset_lower_exclusive, proposal.onset_upper_inclusive) == (dt.date(2020, 12, 31),
                                                                              dt.date(2021, 3, 31))
    assert proposal.timing_class == "interval_uncertain" and len(proposal.evidence_observation_ids) == 4
    record = json.loads((result.projection_path.parent / "package_result.json").read_text())
    assert record["status"] == "parsed"
    assert nport.DeraPackageResult.load(result.projection_path.parent).source_package == result.source_package
