"""Round7 first-release reconciliation (test-only sibling): synthetic bundles.

The retained v2 bundle reuses the replay suite's synthetic builder (T3/T4/T5
stale and T6/T7 missing at the ORIGINAL decision instant) with 40 extra
corroborated candidates so that the Round7 floor admits the synthetic stock
(N = 61, B = 6). The live Round7 bundle is generated by the v3 generator,
audited strictly by the independent auditor and linked to its canary exactly
as the CLIs do, from an upsert-only evolution of the same SEC source. Every
identifier is synthetic; no private custody is read.
"""

from __future__ import annotations

import ast
import copy
import datetime as dt
import hashlib
import json
import os
import stat
import subprocess
import sys
import uuid
from pathlib import Path

import pytest

from scripts import fund_nav_readiness_schema as operator
from scripts import generate_fund_nav_policy_v1 as generator
from scripts import verify_fund_nav_identity_v2 as verifier
from tests import nav_policy_v3_reconcile as reconcile
from tests import nav_policy_v3_replay as replay
from tests import test_nav_policy_v3_replay as base
from tests._nav_identity_fixtures import (
    catalog,
    entity,
    only,
    sec_row,
    synthetic_cusip,
    synthetic_figi,
    synthetic_isin,
)

TAU_V2 = base.TAU
DAY = dt.timedelta(days=1)
SEVEN = dt.timedelta(days=7)
MICRO = dt.timedelta(microseconds=1)
TAU_LIVE = TAU_V2 + 7 * DAY  # a v2 row (TAU_V2 - 1d) not refreshed is 8 days old
POLICY_ID = "current-daily-nav-xnys-usd-adjusted"
POLICY_VERSION = "2026-09-25.3"
V2_FRESH = base.FRESH  # TAU_V2 - 1 day: every matched v2 row
V2_STALE = base.STALE  # TAU_V2 - 30 days
EXTRA = tuple(range(24, 64))  # 40 extra corroborated daily ETFs
EXPECTED = {
    "active_daily_delta": 5,
    "excluded": 5,
    "sec_first_failure": {"sec.missing": 2, "sec.stale": 3},
    "v2": {
        "active": 61,
        "inactive": 1,
        "structural_pre_claims_daily": 60,
        "unknown": 1,
    },
    "v3": {
        "active": 56,
        "inactive": 1,
        "structural_pre_claims_daily": 60,
        "unknown": 6,
    },
}


_BASE_ENTITIES = base._entities  # captured before any monkeypatch of ``base``


def _entities():
    return [*_BASE_ENTITIES(), *(entity(n) for n in EXTRA)]


def _mutated_entities(number: int, mutation: str):
    """A pre-SEC input change that remains internally valid and strict-PASS."""
    entities = copy.deepcopy(_entities())
    iu, fund, registry = entities[number - 1]
    if mutation == "claims":
        replacement = 700 + number
        cusip = synthetic_cusip(replacement)
        isin = synthetic_isin(replacement, cusip=cusip)
        iu["isin"] = fund["isin"] = registry["isin"] = isin
        fund["cusip"] = registry["cusip_9"] = cusip
    elif mutation == "figi":
        registry["figi"] = synthetic_figi(700 + number)
    elif mutation == "fund_type":
        fund["fund_type"] = (
            "etf" if fund["fund_type"] == "mutual_fund" else "mutual_fund"
        )
    else:  # pragma: no cover - closed test helper
        raise AssertionError(mutation)
    return entities


def _v2_sec() -> dict:
    """The retained v2 SEC rows by fund number (poison row 90 included)."""
    rows = {
        n: sec_row(n, synced=V2_STALE if n in base.STALE_IDS else V2_FRESH)
        for n in (*range(1, 22), *EXTRA)
        if n not in base.MISSING_IDS
    }
    rows[90] = sec_row(90, class_id="S000000090:T90", synced=V2_FRESH)
    return rows


@pytest.fixture(scope="module")
def calendar():
    return generator.build_calendar(dt.date(2024, 1, 1), dt.date(2027, 12, 31))


@pytest.fixture(scope="module")
def v2_raw():
    return _v2_raw_with_sec(list(_v2_sec().values()))


def _v2_raw_with_sec(sec):
    with pytest.MonkeyPatch.context() as patch:
        patch.setattr(base, "_entities", _entities)
        docs = base._v2_docs(sec_override=sec)
    return base._raw(docs)


def _synthetic_pins(config: dict) -> None:
    # The production drift baseline (5103) and previous-INACTIVE pin (8979)
    # describe the real catalog; the synthetic population pins its own values.
    config["structural_baseline"] = None
    config["expected_previous_inactive"] = 1


@pytest.fixture
def pinned_config(tmp_path, monkeypatch):
    """The operator's pinned config: the replay's v3 bytes, synthetic pins."""
    raw = base._config(_synthetic_pins)
    path = tmp_path / "pinned-config.json"
    path.write_bytes(raw)
    monkeypatch.setattr(operator, "AUDIT_CONFIG", path)
    return raw


def test_enlarged_v2_bundle_replays_exactly(v2_raw, pinned_config):
    passed, summary = replay.replay(
        *v2_raw, pinned_config, json.dumps(EXPECTED).encode()
    )
    assert passed, base._failed(summary)


# ── live Round7 bundle builder (upsert-only SEC evolution) ──────────────────
def _live_sec(
    tau_live, *, not_refreshed=(), refresh_at=None, rows=None, extra=(), drop=()
):
    """Every v2-fresh row is upserted again just before ``tau_live`` unless in
    ``not_refreshed`` (the v2 stale rows are never refreshed); ``rows``
    replaces single rows, ``extra`` adds rows, ``drop`` removes a row."""
    at = refresh_at or tau_live - dt.timedelta(hours=1)
    evolved = {}
    for n, row in _v2_sec().items():
        if n in drop:
            continue
        refreshed = n not in base.STALE_IDS and n not in not_refreshed
        evolved[n] = dict(row, synced_at=at if refreshed else row["synced_at"])
    evolved.update(rows or {})
    return [*evolved.values(), *extra]


def _previous(calendar) -> bytes:
    document = {
        "policy_id": POLICY_ID,
        "policy_version": "2026-09-23.1",
        "generator_version": "fund-nav-policy-generator-v1",
        "instrument_evidence": [
            {"instrument_id": str(uuid.UUID(int=1)), "fund_status": "ACTIVE"},
            {"instrument_id": str(uuid.UUID(int=23)), "fund_status": "INACTIVE"},
        ],
    }
    for field in verifier.CALENDAR_CONTINUITY_FIELDS:
        document[field] = calendar[field]
    return json.dumps(document, sort_keys=True).encode()


def _live_bundle(
    calendar, config_raw, *, tau_live=TAU_LIVE, sec=None, entities=None, captured=None
):
    """Generate at ``tau_live``, capture the same four sources, audit strictly
    and link the canary exactly as ``verify_fund_nav_identity_v2.main`` does."""
    entities = entities or _entities()
    sec = _live_sec(tau_live) if sec is None else sec
    instruments, funds, identity, sec_rows = catalog(*entities, sec=sec)
    policy = generator.build_policy(
        calendar,
        instruments,
        funds,
        identity,
        sec_rows,
        tau_live,
        POLICY_ID,
        POLICY_VERSION,
    )
    snapshot = generator.build_source_snapshot(
        policy, instruments, funds, identity, sec_rows
    )
    policy_raw = generator.canonical_json(policy)
    config = json.loads(config_raw)
    live = {
        "captured_at": captured or tau_live + dt.timedelta(minutes=5),
        "sources": {"instruments": instruments, "funds": funds, "identity": identity},
        "cohort": {
            "state": "captured",
            "rows": [
                {"instrument_id": uuid.UUID(int=n), "strategy_label": base.LABEL}
                for n in range(1, 23)
            ],
        },
        "sec": {
            "state": "captured",
            "rows": [dict(row) for row in sec_rows],
            "lineage": {
                "row_count": len(sec_rows),
                "min_synced_at": min(row["synced_at"] for row in sec_rows),
                "max_synced_at": max(row["synced_at"] for row in sec_rows),
            },
        },
    }
    capture_raw = verifier.capture_bytes(live, config)
    previous = _previous(calendar)
    report = verifier.audit(
        policy_raw,
        snapshot_raw=generator.canonical_json(snapshot),
        capture_raw=capture_raw,
        previous_raw=previous,
        config_raw=config_raw,
    )
    passed = verifier.verdict_of(report, strict=True)
    report["result"] = "pass" if passed else "fail"
    report["strict"] = True
    report["canary_requested"] = True
    audit_raw = verifier.report_bytes(report)
    canary_raw = operator._document_bytes({})
    if passed:
        canary = verifier.build_canary(
            report,
            policy_raw,
            config,
            audit_report_sha256=hashlib.sha256(audit_raw).hexdigest(),
        )
        canary_raw = (
            json.dumps(canary, sort_keys=True, separators=(",", ":")) + "\n"
        ).encode("ascii")
    return {
        "policy": policy_raw,
        "source_snapshot": generator.canonical_json(snapshot),
        "capture": capture_raw,
        "audit": audit_raw,
        "canary": canary_raw,
        "previous_policy": previous,
    }, report


def _v2_bundle(v2_raw):
    policy_raw, snapshot_raw, capture_raw, audit_raw, v2_config_raw = v2_raw
    bundle = {
        "policy": policy_raw,
        "source_snapshot": snapshot_raw,
        "capture": capture_raw,
        "audit": audit_raw,
    }
    return bundle, v2_config_raw


def _reconcile(v2_raw, live_bundle, config_raw, expected=EXPECTED):
    v2_bundle, v2_config_raw = _v2_bundle(v2_raw)
    return reconcile.reconcile(
        v2_bundle=v2_bundle,
        live_bundle=live_bundle,
        v2_config_raw=v2_config_raw,
        config_raw=config_raw,
        expected_raw=json.dumps(expected).encode(),
    )


def _failed(document):
    return [name for name, ok in document["checks"].items() if not ok]


# ── positive reconciliations ────────────────────────────────────────────────
def test_empty_delta_reconciles_exactly(calendar, v2_raw, pinned_config):
    """Every v2-matched row refreshed: E_live == E23 by identifier and reason."""
    live, report = _live_bundle(calendar, pinned_config, tau_live=TAU_V2 + 3 * DAY)
    assert verifier.verdict_of(report, strict=True)
    passed, document = _reconcile(v2_raw, live, pinned_config)
    assert passed, _failed(document)
    counts = document["counts"]
    assert (counts["e23"], counts["e_live"], counts["retained"]) == (5, 5, 5)
    assert (counts["added_stale"], counts["recovered"]) == (0, 0)
    assert (counts["stale"], counts["missing"], counts["integrity"]) == (3, 2, 0)
    assert (counts["c_size"], counts["bound"]) == (61, 6)
    assert (counts["active"], counts["unknown"], counts["inactive"]) == (56, 6, 1)
    assert (counts["structural_daily"], counts["active_daily"]) == (60, 55)
    assert document["times"]["tau_v2"] == verifier._utc_text(TAU_V2)
    base._assert_shareable(document)


def test_two_new_stale_inside_the_aging_window(calendar, v2_raw, pinned_config):
    """T8/T9 (daily) stopped being refreshed after tau_v2: 8 days old at tau_live."""
    live, report = _live_bundle(
        calendar, pinned_config, sec=_live_sec(TAU_LIVE, not_refreshed={8, 9})
    )
    exclusions = report["details"]["A8"]["exclusions"]
    assert (exclusions["stale"], exclusions["bound"]) == (5, 6)
    passed, document = _reconcile(v2_raw, live, pinned_config)
    assert passed, _failed(document)
    counts = document["counts"]
    assert (counts["added_stale"], counts["e_live"], counts["active"]) == (2, 7, 54)
    assert (counts["added_daily"], counts["active_daily"]) == (2, 53)


def test_several_new_stale_up_to_the_bound(calendar, v2_raw, pinned_config):
    """S = B exactly (3 retained + 3 added = 6 = floor(61 / 10))."""
    live, report = _live_bundle(
        calendar, pinned_config, sec=_live_sec(TAU_LIVE, not_refreshed={8, 9, 10})
    )
    assert report["details"]["A8"]["exclusions"]["stale"] == 6
    passed, document = _reconcile(v2_raw, live, pinned_config)
    assert passed, _failed(document)
    assert document["counts"]["added_stale"] == 3


def test_aging_window_boundary_seven_days_is_fresh_and_1us_ages(
    calendar, v2_raw, pinned_config
):
    """t_last == tau_live - 7d is still fresh (no Delta); 1 microsecond later ages."""
    exact = V2_FRESH + SEVEN
    live, _ = _live_bundle(
        calendar,
        pinned_config,
        tau_live=exact,
        sec=_live_sec(exact, not_refreshed={8}),
        captured=exact,  # T8 stays matched at the decision instant itself
    )
    passed, document = _reconcile(v2_raw, live, pinned_config)
    assert passed and document["counts"]["added_stale"] == 0, _failed(document)
    later = exact + MICRO
    live, _ = _live_bundle(
        calendar, pinned_config, tau_live=later, sec=_live_sec(later, not_refreshed={8})
    )
    passed, document = _reconcile(v2_raw, live, pinned_config)
    assert passed and document["counts"]["added_stale"] == 1, _failed(document)
    assert document["times"]["aging_upper_inclusive"] == verifier._utc_text(
        later - SEVEN
    )


def test_recoveries_of_stale_and_missing_mixed_with_an_addition(
    calendar, v2_raw, pinned_config
):
    """T3 (stale) and T6 (missing) re-listed fresh since tau_v2; T8 ages."""
    fresh = TAU_LIVE - dt.timedelta(hours=2)
    sec = _live_sec(
        TAU_LIVE,
        not_refreshed={8},
        rows={3: sec_row(3, synced=fresh)},
        extra=[sec_row(6, synced=fresh)],
    )
    live, _ = _live_bundle(calendar, pinned_config, sec=sec)
    passed, document = _reconcile(v2_raw, live, pinned_config)
    assert passed, _failed(document)
    counts = document["counts"]
    assert (
        counts["recovered"],
        counts["recovered_stale"],
        counts["recovered_missing"],
    ) == (2, 1, 1)
    assert (counts["added_stale"], counts["retained"]) == (1, 3)
    assert (counts["stale"], counts["missing"]) == (3, 1)
    assert counts["recovered_daily"] == 2


def test_mmf_addition_is_not_counted_as_daily(calendar, v2_raw, pinned_config):
    """T21 (MMF, ACTIVE non-daily) ages: the daily subset is derived, never presumed."""
    live, _ = _live_bundle(
        calendar, pinned_config, sec=_live_sec(TAU_LIVE, not_refreshed={21})
    )
    passed, document = _reconcile(v2_raw, live, pinned_config)
    assert passed, _failed(document)
    counts = document["counts"]
    assert (counts["added_stale"], counts["added_daily"], counts["active_daily"]) == (
        1,
        0,
        55,
    )


@pytest.mark.parametrize(
    "role,number,mutation",
    [
        ("delta", 8, "claims"),
        ("recovery", 3, "claims"),
        ("active", 10, "claims"),
        ("active", 10, "figi"),
        ("active", 10, "fund_type"),
    ],
)
def test_complete_pre_sec_identity_must_be_unchanged(
    calendar, v2_raw, pinned_config, role, number, mutation
):
    """Valid, internally consistent claim/input replacement is still drift.

    The same private projection is applied to unchanged ACTIVE, Delta and R;
    no moved identifier bypasses the pre-SEC comparison.
    """
    entities = _mutated_entities(number, mutation)
    if role == "delta":
        sec = _live_sec(TAU_LIVE, not_refreshed={number})
    elif role == "recovery":
        sec = _live_sec(
            TAU_LIVE,
            rows={number: sec_row(number, synced=TAU_LIVE - dt.timedelta(hours=1))},
        )
    else:
        sec = _live_sec(TAU_LIVE)
    live, report = _live_bundle(calendar, pinned_config, entities=entities, sec=sec)
    assert verifier.verdict_of(report, strict=True), report["gates"]
    passed, document = _reconcile(v2_raw, live, pinned_config)
    assert not passed and document["status"] == "stop"
    assert document["counts"]["non_sec_changes"] >= 1
    assert not document["checks"]["universe_and_pre_sec_unchanged"]
    assert not document["checks"]["only_sec_movements"]
    base._assert_shareable(document)


@pytest.mark.parametrize(
    "case",
    [
        "matched_moves_back_other_advances",
        "older_related_disappears",
        "matched_row_disappears",
    ],
)
def test_delta_requires_exact_per_row_sec_continuity(calendar, pinned_config, case):
    """No aggregate timestamp or other related row can replace continuity."""
    old_related = sec_row(808, ticker="T8", series="S000000008", synced=V2_STALE)
    historical = _v2_raw_with_sec([*_v2_sec().values(), old_related])
    if case == "matched_moves_back_other_advances":
        sec = _live_sec(
            TAU_LIVE,
            rows={8: sec_row(8, synced=V2_FRESH - 2 * DAY)},
            extra=[sec_row(808, ticker="T8", series="S000000008", synced=V2_FRESH)],
        )
    elif case == "older_related_disappears":
        sec = _live_sec(TAU_LIVE, not_refreshed={8})
    else:  # matched_row_disappears
        sec = _live_sec(TAU_LIVE, drop={8}, extra=[old_related])
    live, report = _live_bundle(calendar, pinned_config, sec=sec)
    assert verifier.verdict_of(report, strict=True), report["gates"]
    passed, document = _reconcile(historical, live, pinned_config)
    assert not passed and document["status"] == "stop"
    assert not document["checks"]["additions_aging_window"]
    assert document["counts"]["invalid_additions"] == 1
    base._assert_shareable(document)


# ── negative reconciliations (STOP or blocked, sanitized) ───────────────────
@pytest.mark.parametrize(
    "case,failed",
    [
        # A mapping that disappeared: a new missing, never an aged listing.
        ("new_missing", {"additions_stale_only", "counts_conserved"}),
        # The retained key's timestamp moved BACKWARDS (source reconstruction).
        ("reconstructed_older_row", {"additions_aging_window"}),
        # A new related (same ticker) historical identity appeared.
        ("new_related_identity", {"additions_aging_window"}),
        # A retained missing fund now has an OLD row: relabel missing -> stale.
        ("relabel_missing_to_stale", {"intersection_reasons_unchanged"}),
        # Fresh at tau_live, but the listing predates tau_v2: no relisting.
        ("fresh_without_new_listing", {"removals_fresh_relisted"}),
        # A non-SEC decision moved (activity unknown -> active).
        (
            "non_sec_decision_moved",
            {"universe_and_pre_sec_unchanged", "only_sec_movements"},
        ),
        # A retained missing fund leaves E through a lost registry claim, not a
        # fresh relisting: an invalid removal and a changed pre-SEC set.
        (
            "removal_by_lost_registry",
            {"removals_fresh_relisted", "universe_and_pre_sec_unchanged"},
        ),
    ],
)
def test_reconciliation_stops_on_unexplained_movement(
    calendar, v2_raw, pinned_config, case, failed
):
    tau_live, entities = TAU_LIVE, None
    if case == "new_missing":
        sec = _live_sec(tau_live, drop={8})
    elif case == "reconstructed_older_row":
        sec = _live_sec(tau_live, rows={8: sec_row(8, synced=V2_FRESH - 2 * DAY)})
    elif case == "new_related_identity":
        sec = _live_sec(
            tau_live,
            not_refreshed={8},
            extra=[sec_row(808, ticker="T8", series="S000000008", synced=V2_FRESH)],
        )
    elif case == "relabel_missing_to_stale":
        sec = _live_sec(tau_live, extra=[sec_row(6, synced=V2_STALE)])
    elif case == "fresh_without_new_listing":
        tau_live = TAU_V2 + 3 * DAY
        sec = _live_sec(
            tau_live, rows={3: sec_row(3, synced=TAU_V2 - dt.timedelta(hours=1))}
        )
    elif case == "removal_by_lost_registry":
        entities = _entities()
        entities[5] = only(entity(6), registry=False)
        sec = _live_sec(tau_live, extra=[sec_row(6, synced=tau_live - DAY)])
    else:  # non_sec_decision_moved
        entities = _entities()
        entities[21] = entity(22)
        sec = _live_sec(tau_live, extra=[sec_row(22, synced=tau_live - DAY)])
    live, report = _live_bundle(
        calendar, pinned_config, tau_live=tau_live, sec=sec, entities=entities
    )
    assert verifier.verdict_of(report, strict=True), report["gates"]
    passed, document = _reconcile(v2_raw, live, pinned_config)
    assert not passed and document["status"] == "stop"
    assert failed <= set(_failed(document)), _failed(document)
    base._assert_shareable(document)


def test_new_integrity_exclusion_fails_the_live_audit_and_blocks(
    calendar, v2_raw, pinned_config
):
    """A contradiction (K = 1) FAILs A8: the live bundle is never strict PASS."""
    sec = _live_sec(
        TAU_LIVE, rows={8: sec_row(8, series="S000000099", synced=TAU_LIVE - DAY)}
    )
    live, report = _live_bundle(calendar, pinned_config, sec=sec)
    assert report["gates"]["A8"]["checks"]["sec_integrity_zero"] is False
    with pytest.raises(
        reconcile.ReconcileBlocked, match="operator:audit_dossier_invalid"
    ):
        _reconcile(v2_raw, live, pinned_config)


def test_stale_over_the_bound_fails_the_live_audit_and_blocks(
    calendar, v2_raw, pinned_config
):
    live, report = _live_bundle(
        calendar, pinned_config, sec=_live_sec(TAU_LIVE, not_refreshed={8, 9, 10, 11})
    )
    assert report["gates"]["A8"]["checks"]["sec_stale_within_bound"] is False
    with pytest.raises(
        reconcile.ReconcileBlocked, match="operator:audit_dossier_invalid"
    ):
        _reconcile(v2_raw, live, pinned_config)


def test_historical_replay_must_pass_exactly(calendar, v2_raw, pinned_config):
    live, _ = _live_bundle(calendar, pinned_config, tau_live=TAU_V2 + 3 * DAY)
    wrong = copy.deepcopy(EXPECTED)
    wrong["excluded"] = 6
    passed, document = _reconcile(v2_raw, live, pinned_config, expected=wrong)
    assert not passed and "historical_replay_exact" in _failed(document)


def test_live_before_v2_is_blocked(calendar, v2_raw, pinned_config):
    early = TAU_V2 - dt.timedelta(hours=2)
    live, report = _live_bundle(
        calendar,
        pinned_config,
        tau_live=early,
        sec=_live_sec(early, refresh_at=early - DAY),
    )
    assert verifier.verdict_of(report, strict=True), report["gates"]
    with pytest.raises(
        reconcile.ReconcileBlocked, match="reconcile_time_order_invalid"
    ):
        _reconcile(v2_raw, live, pinned_config)


def test_live_config_must_be_the_repository_pin(
    calendar, v2_raw, pinned_config, tmp_path, monkeypatch
):
    live, _ = _live_bundle(calendar, pinned_config)
    other = tmp_path / "other.json"
    other.write_bytes(pinned_config + b" ")
    monkeypatch.setattr(operator, "AUDIT_CONFIG", other)
    with pytest.raises(
        reconcile.ReconcileBlocked, match="audit_config_not_repository_pin"
    ):
        _reconcile(v2_raw, live, pinned_config)


@pytest.mark.parametrize(
    "mutate,code",
    [
        (
            lambda d: d["inputs"].update(
                audit_contract_version="nav-identity-audit-contract-v3-round6"
            ),
            "operator:audit_contract_mismatch",
        ),
        (
            lambda d: d["gates"]["A8"].update(status="FAIL"),
            "operator:audit_not_strict_pass",
        ),
        (
            lambda d: d["details"]["A8"]["exclusions"].update(stale=2),
            "operator:audit_dossier_invalid",
        ),
    ],
    ids=["round6_live_dossier", "auditor_not_pass", "exclusions_tampered"],
)
def test_round6_failed_or_tampered_live_dossier_is_blocked(
    calendar, v2_raw, pinned_config, mutate, code
):
    live, _ = _live_bundle(calendar, pinned_config)
    dossier = json.loads(live["audit"])
    mutate(dossier)
    live["audit"] = verifier.report_bytes(dossier)
    with pytest.raises(reconcile.ReconcileBlocked, match=code):
        _reconcile(v2_raw, live, pinned_config)


def test_round6_capture_kind_is_blocked(calendar, v2_raw, pinned_config):
    live, _ = _live_bundle(calendar, pinned_config)
    capture = json.loads(live["capture"])
    capture["kind"] = "nav-identity-audit-capture-v3-round6"
    live["capture"] = operator._document_bytes(capture)
    with pytest.raises(
        reconcile.ReconcileBlocked, match="operator:audit_capture_mismatch"
    ):
        _reconcile(v2_raw, live, pinned_config)


def test_reaudited_dossier_must_equal_the_pinned_one(
    calendar, v2_raw, pinned_config, monkeypatch
):
    """A dossier that the independent re-audit does not reproduce byte-for-byte."""
    live, _ = _live_bundle(calendar, pinned_config)
    original = verifier.report_bytes
    monkeypatch.setattr(
        verifier, "report_bytes", lambda report: original(report) + b" "
    )
    passed, document = _reconcile(v2_raw, live, pinned_config)
    assert not passed and "live_round7_strict_bound" in _failed(document)


def test_bundle_shape_is_validated_before_any_work(calendar, v2_raw, pinned_config):
    live, _ = _live_bundle(calendar, pinned_config)
    live.pop("previous_policy")
    with pytest.raises(reconcile.ReconcileBlocked, match="reconcile_bundle_invalid"):
        _reconcile(v2_raw, live, pinned_config)


def test_wrong_previous_policy_is_blocked(calendar, v2_raw, pinned_config):
    live, _ = _live_bundle(calendar, pinned_config)
    live["previous_policy"] = live["previous_policy"] + b" "
    with pytest.raises(
        reconcile.ReconcileBlocked, match="live_previous_policy_mismatch"
    ):
        _reconcile(v2_raw, live, pinned_config)


# ── closed public schema, blocked codes and module boundaries ───────────────
def test_public_report_is_closed_and_rejects_identifiers(
    calendar, v2_raw, pinned_config
):
    live, _ = _live_bundle(calendar, pinned_config)
    _passed, document = _reconcile(v2_raw, live, pinned_config)
    assert tuple(document) == reconcile.PUBLIC_KEYS
    assert tuple(document["code_sha256"]) == reconcile.CODE_FILES
    assert tuple(document["inputs"]) == reconcile.INPUT_KEYS
    assert tuple(document["checks"]) == reconcile.CHECK_NAMES
    assert tuple(document["counts"]) == reconcile.COUNT_KEYS
    reconcile.validate_public(document)

    def flip(d):
        d["checks"]["counts_conserved"] = not d["checks"]["counts_conserved"]

    for mutate in (
        lambda d: d["counts"].update(e23=True),
        lambda d: d["counts"].update(e23=-1),
        lambda d: d["checks"].update(additions_stale_only=1),
        lambda d: d["times"].update(tau_v2="2026-09-23T10:00:00"),
        lambda d: d["inputs"].update(v2_policy=str(uuid.UUID(int=1))),
        lambda d: d.update(extra=1),
        lambda d: d["counts"].update(ticker=1),
        flip,  # status no longer equals all(checks)
    ):
        broken = copy.deepcopy(document)
        mutate(broken)
        with pytest.raises(
            reconcile.ReconcileBlocked, match="reconcile_output_not_sanitized"
        ):
            reconcile.validate_public(broken)


def test_blocked_codes_are_allowlisted():
    assert reconcile.blocked_code("operator:audit_contract_mismatch") == (
        "operator:audit_contract_mismatch"
    )
    assert (
        reconcile.blocked_code("live_policy_sha256_mismatch")
        == "live_policy_sha256_mismatch"
    )
    for leaked in (
        f"operator:{uuid.UUID(int=1)}",
        "Traceback (most recent call last)",
        "x" * 300,
        "sql:DROP TABLE",
        "operator:T8 C000000008",
        "other:code",
    ):
        assert reconcile.blocked_code(leaked) == "reconcile_code_not_allowlisted"


def test_reconcile_is_test_only_and_reuses_the_replay():
    root = Path(reconcile.__file__).parents[1]
    for directory in ("scripts", "src"):
        for path in (root / directory).rglob("*.py"):
            assert "nav_policy_v3_reconcile" not in path.read_text(encoding="utf-8"), (
                path
            )
    source = Path(reconcile.__file__).read_text(encoding="utf-8")
    tree = ast.parse(source)
    imported = {
        alias.name
        for node in ast.walk(tree)
        if isinstance(node, ast.ImportFrom) and node.module in ("scripts", "tests")
        for alias in node.names
    }
    assert imported == {
        "fund_nav_readiness_schema",
        "generate_fund_nav_policy_v1",
        "verify_fund_nav_identity_v2",
        "nav_policy_v3_replay",
    }
    attributes = {
        node.attr for node in ast.walk(tree) if isinstance(node, ast.Attribute)
    }
    assert "replay_state" in attributes  # E23 by identifier from the exact replay
    for forbidden in (
        "psycopg",
        "--dsn",
        "--expected",
        "--tolerance",
        "--now",
        "urllib",
    ):
        assert forbidden not in source
    # The historical replay keeps its CODE_FILES and two-value API.
    assert replay.CODE_FILES == (
        "scripts/generate_fund_nav_policy_v1.py",
        "scripts/verify_fund_nav_identity_v2.py",
        "scripts/nav_identity_audit_contract.py",
        "src/workers/_nav_policy.py",
        "tests/nav_policy_v3_replay.py",
    )
    assert reconcile.CODE_FILES == (
        *replay.CODE_FILES,
        "scripts/fund_nav_readiness_schema.py",
        "tests/nav_policy_v3_reconcile.py",
    )


# ── CLI (POSIX custody) ─────────────────────────────────────────────────────
def _cli_args(
    tmp_path, v2_raw, live, config_raw, *, monkeypatch, output=None, custody=None
):
    root = tmp_path / "custody"
    root.mkdir(mode=0o700)
    v2_bundle, v2_config_raw = _v2_bundle(v2_raw)
    args = []
    for prefix, bundle in (("v2", v2_bundle), ("live", live)):
        for key, raw in bundle.items():
            path = root / f"{prefix}-{key}.json"
            path.write_bytes(raw)
            flag = f"{prefix}-{key.replace('_', '-')}"
            args += [
                f"--{flag}-file",
                str(path),
                f"--{flag}-sha256",
                hashlib.sha256(raw).hexdigest(),
            ]
    (root / "v2-config.json").write_bytes(v2_config_raw)
    (root / "config.json").write_bytes(config_raw)
    expected = tmp_path / "expected.json"
    expected.write_bytes(json.dumps(EXPECTED).encode())
    monkeypatch.setattr(reconcile, "EXPECTED_PATH", expected)
    args += [
        "--v2-audit-config",
        str(root / "v2-config.json"),
        "--audit-config",
        str(root / "config.json"),
        "--custody-root",
        str(custody or root),
        "--output",
        str(output or root / "reconcile.json"),
    ]
    return root, args


@pytest.mark.skipif(os.name != "posix", reason="private custody is POSIX-only")
def test_cli_pass_writes_a_private_sanitized_report_once(
    calendar, v2_raw, pinned_config, tmp_path, capsys, monkeypatch
):
    live, _ = _live_bundle(
        calendar, pinned_config, sec=_live_sec(TAU_LIVE, not_refreshed={8})
    )
    root, args = _cli_args(
        tmp_path, v2_raw, live, pinned_config, monkeypatch=monkeypatch
    )
    assert reconcile.main(args) == 0, capsys.readouterr().out
    printed = capsys.readouterr().out
    base._assert_text_shareable(printed)
    report = root / "reconcile.json"
    written = report.read_bytes()
    assert stat.S_IMODE(report.stat().st_mode) == 0o600
    stdout_document = json.loads(printed)
    document = json.loads(written)
    reconcile.validate_output(stdout_document)
    reconcile.validate_public(document)
    assert stdout_document == document
    assert document["status"] == "pass" and document["counts"]["added_stale"] == 1
    assert reconcile.main(args) == 2  # never overwritten
    blocked = json.loads(capsys.readouterr().out)
    reconcile.validate_output(blocked)
    assert report.read_bytes() == written


@pytest.mark.skipif(os.name != "posix", reason="private custody is POSIX-only")
def test_cli_stop_is_exit_3_and_sanitized(
    calendar, v2_raw, pinned_config, tmp_path, capsys, monkeypatch
):
    live, _ = _live_bundle(calendar, pinned_config, sec=_live_sec(TAU_LIVE, drop={8}))
    root, args = _cli_args(
        tmp_path, v2_raw, live, pinned_config, monkeypatch=monkeypatch
    )
    assert reconcile.main(args) == 3
    printed = capsys.readouterr().out
    base._assert_text_shareable(printed)
    stdout_document = json.loads(printed)
    document = json.loads((root / "reconcile.json").read_bytes())
    reconcile.validate_output(stdout_document)
    reconcile.validate_public(document)
    assert stdout_document == document
    assert (
        document["status"] == "stop" and not document["checks"]["additions_stale_only"]
    )


@pytest.mark.skipif(os.name != "posix", reason="private custody is POSIX-only")
@pytest.mark.parametrize(
    "case",
    ["wrong_sha", "symlink_output", "outside_output", "no_custody", "blocked_live"],
)
def test_cli_blocks_with_static_code_only(
    calendar, v2_raw, pinned_config, tmp_path, capsys, monkeypatch, case
):
    sec = (
        _live_sec(TAU_LIVE, not_refreshed={8, 9, 10, 11})
        if case == "blocked_live"
        else None
    )
    live, _ = _live_bundle(calendar, pinned_config, sec=sec)
    output = tmp_path / "outside.json" if case == "outside_output" else None
    custody = tmp_path / "absent" if case == "no_custody" else None
    root, args = _cli_args(
        tmp_path,
        v2_raw,
        live,
        pinned_config,
        monkeypatch=monkeypatch,
        output=output,
        custody=custody,
    )
    if case == "wrong_sha":
        args[args.index("--live-policy-sha256") + 1] = "0" * 64
    elif case == "symlink_output":
        (root / "target.json").write_bytes(b"{}")
        os.symlink(root / "target.json", root / "reconcile.json")
    assert reconcile.main(args) == 2
    printed = capsys.readouterr().out
    blocked = json.loads(printed)
    reconcile.validate_output(blocked)
    assert "Traceback" not in printed and str(tmp_path) not in printed
    base._assert_text_shareable(printed)
    expected = {
        "wrong_sha": "live_policy_sha256_mismatch",
        "blocked_live": "operator:audit_dossier_invalid",
    }
    if case in expected:
        assert blocked["code"] == expected[case]
    assert not (tmp_path / "outside.json").exists()
    if case == "symlink_output":
        assert (root / "target.json").read_bytes() == b"{}"


@pytest.mark.parametrize(
    "case",
    ["unknown", "positional", "missing", "duplicate", "option_as_value"],
)
def test_cli_shape_errors_are_silent_closed_and_read_nothing(
    calendar,
    v2_raw,
    pinned_config,
    tmp_path,
    capsys,
    monkeypatch,
    case,
):
    sentinel = "PRIVATE_SENTINEL_PATH_AND_ARGUMENT"
    live, _ = _live_bundle(calendar, pinned_config)
    _root, valid = _cli_args(
        tmp_path, v2_raw, live, pinned_config, monkeypatch=monkeypatch
    )
    if case == "unknown":
        argv = [f"--unknown-{sentinel}", sentinel]
    elif case == "positional":
        argv = [sentinel]
    elif case == "missing":
        argv = valid[:-2]
    elif case == "duplicate":
        argv = list(valid)
        argv[0] = argv[2]
        argv[1] = sentinel
    else:
        argv = list(valid)
        argv[1] = "--v2-source-snapshot-file"
    monkeypatch.setattr(
        replay,
        "_read_pinned",
        lambda *_args, **_kwargs: (_ for _ in ()).throw(AssertionError("file read")),
    )
    assert reconcile.main(argv) == 2
    captured = capsys.readouterr()
    assert captured.err == ""
    assert sentinel not in captured.out and "usage:" not in captured.out.lower()
    document = json.loads(captured.out)
    reconcile.validate_output(document)
    assert document == {"status": "blocked", "code": "reconcile_cli_invalid"}


def test_cli_subprocess_never_echoes_private_invalid_argv():
    sentinel = "PRIVATE_SENTINEL_SUBPROCESS_PATH"
    completed = subprocess.run(
        [
            sys.executable,
            "-m",
            "tests.nav_policy_v3_reconcile",
            f"--unknown-{sentinel}",
            sentinel,
        ],
        cwd=Path(reconcile.__file__).parents[1],
        capture_output=True,
        text=True,
        check=False,
    )
    assert completed.returncode == 2
    assert completed.stderr == ""
    assert sentinel not in completed.stdout and "usage:" not in completed.stdout.lower()
    document = json.loads(completed.stdout)
    reconcile.validate_output(document)
    assert document == {"status": "blocked", "code": "reconcile_cli_invalid"}
