"""Column ownership contract for ``fund_risk_metrics``.

The table is intentionally wide because several recurring workers enrich the
same latest risk row. This registry is the source of truth used by tests and by
worker modules so new columns cannot be added without an explicit owner.
"""

from __future__ import annotations

OWNER_CORE = "core"
OWNER_RISK_METRICS = "risk_metrics"
OWNER_ACTIVE_SHARE = "active_share"
OWNER_MOMENTUM = "momentum"
OWNER_RESERVED = "reserved"

CORE_COLUMNS = (
    "instrument_id",
    "calc_date",
    "organization_id",
)

RISK_METRICS_UPSERT_COLUMNS = (
    "cvar_95_1m", "cvar_95_3m", "cvar_95_6m", "cvar_95_12m",
    "var_95_1m", "var_95_3m", "var_95_6m", "var_95_12m",
    "return_1m", "return_3m", "return_6m", "return_1y",
    "return_3y_ann", "return_5y_ann", "return_10y_ann",
    "volatility_1y", "volatility_garch", "vol_model",
    "max_drawdown_1y", "max_drawdown_3y",
    "sharpe_1y", "sharpe_3y", "sortino_1y", "calmar_ratio_3y",
    "alpha_1y", "beta_1y", "tracking_error_1y",
    "information_ratio_1y", "upside_capture_1y", "downside_capture_1y",
    "equity_correlation_252d",
    "sharpe_cf", "sharpe_cf_skew", "sharpe_cf_kurt",
    "sharpe_cf_ci_lower", "sharpe_cf_ci_upper",
    "cvar_99_evt", "cvar_999_evt", "evt_xi_shape",
    "fed_funds_rate_at_calc", "data_quality_flags",
    "scoring_model",
    "empirical_duration", "empirical_duration_r2",
    "credit_beta", "credit_beta_r2",
    "inflation_beta", "inflation_beta_r2",
    "crisis_alpha_score",
    "nav_quality_ok", "nav_glitch_count",
)

RISK_METRICS_POST_STEP_COLUMNS = (
    "peer_strategy_label",
    "peer_sharpe_pctl",
    "peer_sortino_pctl",
    "peer_return_pctl",
    "peer_drawdown_pctl",
    "peer_count",
    "peer_overall_quartile",
    "peer_band_low",
    "peer_band_mid",
    "peer_band_high",
    "manager_score",
)

ACTIVE_SHARE_COLUMNS = (
    "active_share_normalized",
    "overlap_normalized",
    "overlap_nav_raw",
    "fund_cusip_coverage_nav",
    "benchmark_cusip_coverage_nav",
    "n_fund_holdings",
    "n_benchmark_holdings",
    "n_common_holdings",
    "n_fund_only",
    "n_benchmark_only",
    "holdings_jaccard",
    "fund_report_age_days",
    "benchmark_report_age_days",
    "report_date_gap_days",
    "active_share_benchmark_instrument_id",
    "active_share_benchmark_series_id",
    "active_share_fund_report_date",
    "active_share_benchmark_report_date",
)

MOMENTUM_COLUMNS = (
    "dtw_drift_score",
    "rsi_14",
    "bb_position",
    "nav_momentum_score",
    "flow_momentum_score",
    "blended_momentum_score",
)

LATENT_MMF_COLUMNS = (
    "seven_day_net_yield",
    "nav_per_share_mmf",
    "pct_weekly_liquid",
    "weighted_avg_maturity_days",
)

RESERVED_COLUMNS = (
    "elite_flag",
    "score_components",
    "elite_rank_within_strategy",
    "elite_target_count_per_strategy",
    "cvar_95_conditional",
    "yield_proxy_12m",
    "duration_adj_drawdown_1y",
)

FUND_RISK_METRICS_COLUMNS = (
    "instrument_id",
    "calc_date",
    "organization_id",
    "cvar_95_1m",
    "cvar_95_3m",
    "cvar_95_6m",
    "cvar_95_12m",
    "var_95_1m",
    "var_95_3m",
    "var_95_6m",
    "var_95_12m",
    "return_1m",
    "return_3m",
    "return_6m",
    "return_1y",
    "return_3y_ann",
    "return_5y_ann",
    "return_10y_ann",
    "volatility_1y",
    "volatility_garch",
    "vol_model",
    "max_drawdown_1y",
    "max_drawdown_3y",
    "sharpe_1y",
    "sharpe_3y",
    "sortino_1y",
    "calmar_ratio_3y",
    "alpha_1y",
    "beta_1y",
    "tracking_error_1y",
    "information_ratio_1y",
    "upside_capture_1y",
    "downside_capture_1y",
    "sharpe_cf",
    "sharpe_cf_skew",
    "sharpe_cf_kurt",
    "sharpe_cf_ci_lower",
    "sharpe_cf_ci_upper",
    "cvar_99_evt",
    "cvar_999_evt",
    "evt_xi_shape",
    "fed_funds_rate_at_calc",
    "data_quality_flags",
    "peer_strategy_label",
    "peer_sharpe_pctl",
    "peer_sortino_pctl",
    "peer_return_pctl",
    "peer_drawdown_pctl",
    "peer_count",
    "manager_score",
    "elite_flag",
    "equity_correlation_252d",
    "empirical_duration",
    "credit_beta",
    "crisis_alpha_score",
    "inflation_beta",
    "active_share_normalized",
    "overlap_normalized",
    "overlap_nav_raw",
    "fund_cusip_coverage_nav",
    "benchmark_cusip_coverage_nav",
    "n_fund_holdings",
    "n_benchmark_holdings",
    "n_common_holdings",
    "n_fund_only",
    "n_benchmark_only",
    "holdings_jaccard",
    "fund_report_age_days",
    "benchmark_report_age_days",
    "report_date_gap_days",
    "active_share_benchmark_instrument_id",
    "active_share_benchmark_series_id",
    "active_share_fund_report_date",
    "active_share_benchmark_report_date",
    "score_components",
    "dtw_drift_score",
    "rsi_14",
    "bb_position",
    "nav_momentum_score",
    "flow_momentum_score",
    "blended_momentum_score",
    "cvar_95_conditional",
    "elite_rank_within_strategy",
    "elite_target_count_per_strategy",
    "empirical_duration_r2",
    "credit_beta_r2",
    "yield_proxy_12m",
    "duration_adj_drawdown_1y",
    "scoring_model",
    "inflation_beta_r2",
    "peer_overall_quartile",
    "peer_band_low",
    "peer_band_mid",
    "peer_band_high",
    "nav_quality_ok",
    "nav_glitch_count",
)

FUND_RISK_COLUMN_OWNERS = {
    **{c: OWNER_CORE for c in CORE_COLUMNS},
    **{c: OWNER_RISK_METRICS for c in RISK_METRICS_UPSERT_COLUMNS},
    **{c: OWNER_RISK_METRICS for c in RISK_METRICS_POST_STEP_COLUMNS},
    **{c: OWNER_ACTIVE_SHARE for c in ACTIVE_SHARE_COLUMNS},
    **{c: OWNER_MOMENTUM for c in MOMENTUM_COLUMNS},
    **{c: OWNER_RESERVED for c in RESERVED_COLUMNS},
}

FUND_RISK_LATEST_MV_COLUMNS = (
    "instrument_id",
    "calc_date",
    "return_1m",
    "return_3m",
    "return_1y",
    "return_3y_ann",
    "return_5y_ann",
    "volatility_1y",
    "volatility_garch",
    "vol_model",
    "max_drawdown_1y",
    "max_drawdown_3y",
    "sharpe_1y",
    "sharpe_3y",
    "sortino_1y",
    "calmar_ratio_3y",
    "alpha_1y",
    "beta_1y",
    "information_ratio_1y",
    "tracking_error_1y",
    "var_95_1m",
    "cvar_95_1m",
    "cvar_95_12m",
    "cvar_99_evt",
    "cvar_999_evt",
    "evt_xi_shape",
    "peer_sharpe_pctl",
    "peer_sortino_pctl",
    "peer_return_pctl",
    "peer_drawdown_pctl",
    "peer_overall_quartile",
    "peer_band_low",
    "peer_band_mid",
    "peer_band_high",
    "manager_score",
    "downside_capture_1y",
    "upside_capture_1y",
    "equity_correlation_252d",
    "peer_strategy_label",
    "peer_count",
    "empirical_duration",
    "empirical_duration_r2",
    "credit_beta",
    "credit_beta_r2",
    "inflation_beta",
    "inflation_beta_r2",
    "crisis_alpha_score",
    "scoring_model",
    "active_share_normalized",
    "overlap_normalized",
    "overlap_nav_raw",
    "fund_cusip_coverage_nav",
    "benchmark_cusip_coverage_nav",
    "n_fund_holdings",
    "n_benchmark_holdings",
    "n_common_holdings",
    "n_fund_only",
    "n_benchmark_only",
    "holdings_jaccard",
    "fund_report_age_days",
    "benchmark_report_age_days",
    "report_date_gap_days",
    "active_share_benchmark_instrument_id",
    "active_share_benchmark_series_id",
    "active_share_fund_report_date",
    "active_share_benchmark_report_date",
    "dtw_drift_score",
    "rsi_14",
    "bb_position",
    "nav_momentum_score",
    "flow_momentum_score",
    "blended_momentum_score",
    "nav_quality_ok",
    "nav_glitch_count",
)

FUND_RISK_LATEST_MV_STALE_POLICIES = {
    OWNER_ACTIVE_SHARE: (
        "Snapshot from the latest available N-PORT reports at or before "
        "calc_date; active_share_*_report_date and *_age_days are exposed."
    ),
}
