"""Reproduce the NAV readiness catalog manifest on a disposable local database.

Default mode compares the committed manifest byte-for-byte and writes nothing;
``--write`` replaces only ``schemas/fund_nav_readiness_v1.catalog.json``.

The extractor, canonicalization and DDL application are imported from the
operator (``catalog_signature``/``apply_ddl``): generator and checker cannot
diverge. The reference server must be exactly the pinned PostgreSQL/TimescaleDB
version, reached on loopback in a ``nav_readiness_w1*`` database; a random
schema is created, applied like production and dropped in ``finally``. No
existing schema, production connection or provider is touched.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import os
import sys
import uuid
from pathlib import Path

import psycopg
from psycopg import sql

from scripts import fund_nav_readiness_schema as operator
from src.workers._nav_policy import canonical_digest

ROOT = Path(__file__).resolve().parents[1]
MANIFEST = operator.CATALOG_MANIFEST
DDL = operator.DDL
NAV_DDL = ROOT / "schemas" / "instrument_ingestion.sql"
POSTGRES_VERSION_NUM = 180004
TIMESCALEDB_VERSION = "2.27.2"
COMMENT = (
    "Semantic catalog of a fresh operator apply of fund_nav_readiness_v1.sql on "
    "PostgreSQL 18.4 / TimescaleDB 2.27.2. Generated by "
    "`python -m scripts.generate_fund_nav_readiness_catalog --write`; never edit."
)


def manifest_bytes(signature: dict, ddl: bytes) -> bytes:
    manifest = {
        "comment": COMMENT,
        "ddl_sha256": hashlib.sha256(ddl).hexdigest(),
        "postgres_version_num": POSTGRES_VERSION_NUM,
        "timescaledb_version": TIMESCALEDB_VERSION,
        "signature_sha256": canonical_digest(signature),
        "signature": signature,
    }
    return (json.dumps(manifest, indent=1, sort_keys=True) + "\n").encode("utf-8")


def _require_reference_server(dsn: str) -> None:
    parsed = psycopg.conninfo.conninfo_to_dict(dsn)
    if parsed.get("host") not in ("127.0.0.1", "localhost", "::1") or not parsed.get(
        "dbname", ""
    ).startswith("nav_readiness_w1"):
        raise ValueError("disposable_local_nav_database_required")
    with psycopg.connect(dsn, connect_timeout=5) as conn:
        version, extension = conn.execute(
            "SELECT current_setting('server_version_num')::int, "
            "(SELECT extversion FROM pg_extension WHERE extname='timescaledb')"
        ).fetchone()
    if version != POSTGRES_VERSION_NUM or extension != TIMESCALEDB_VERSION:
        raise ValueError(
            f"reference_server_mismatch:{version}/{extension}"
            f" expected {POSTGRES_VERSION_NUM}/{TIMESCALEDB_VERSION}"
        )


def fresh_signature(dsn: str) -> dict:
    """Signature of a brand-new schema with the prerequisites plus operator DDL."""
    _require_reference_server(dsn)
    schema = "nav_catalog_" + uuid.uuid4().hex
    with psycopg.connect(dsn, autocommit=True, connect_timeout=5) as conn:
        conn.execute(sql.SQL("CREATE SCHEMA {}").format(sql.Identifier(schema)))
        try:
            # Prerequisite nav_timeseries hypertable (create_hypertable lives in public).
            conn.execute(
                sql.SQL("SET search_path TO {}, public").format(sql.Identifier(schema))
            )
            conn.execute(NAV_DDL.read_text(encoding="utf-8"))
            operator.apply_ddl(conn, schema, DDL.read_bytes())
            conn.execute("BEGIN TRANSACTION READ ONLY")
            try:
                signature = operator.catalog_signature(conn, schema)
            finally:
                conn.execute("ROLLBACK")
        finally:
            conn.execute(sql.SQL("RESET search_path"))
            conn.execute(
                sql.SQL("DROP SCHEMA {} CASCADE").format(sql.Identifier(schema))
            )
    # JSON round-trip: the manifest stores JSON types (tuples become lists).
    return json.loads(json.dumps(signature))


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--write", action="store_true", help="replace the generated manifest"
    )
    args = parser.parse_args(argv)
    dsn = os.environ["NAV_W1_TEST_DSN"]
    expected = manifest_bytes(fresh_signature(dsn), DDL.read_bytes())
    digest = hashlib.sha256(expected).hexdigest()
    if args.write:
        MANIFEST.write_bytes(expected)
        print(f"catalog_manifest_written sha256={digest}")
        return 0
    if MANIFEST.read_bytes() != expected:
        print("catalog_manifest_stale", file=sys.stderr)
        return 1
    print(f"catalog_manifest_current sha256={digest}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
